### ISSUE TITLE
Update the code generator to python 3

### ISSUE THREAD

**Issue by vitamins** [robshakir/pyangbind#10]
My pyang version uses python3, and i think that this requires pyangbind to use python3 as well.
Run the program "2to3" on the .py files. You can see that there are only few lines of code that need to be changed.
Run "2to3 -w pybind.py" and "2to3 -w lib/yangtypes.py" and "2to3 -w lib/xpathhelper.py" to update.
The generated code itself must be ported to python 3 separately.

**Comment by robshakir** [comment]
Hi!

Thanks for the request -- this is certainly something that I can look at adding. Did you try the generated code with python3?

Thanks,
r.

**Comment by vitamins** [comment]
I can not generate code with pyangbind when the up-to-date python3 version of pyang is installed.
After installing the outdated python2 version of pyang, pyangbind works.

When i try to import the generated code in python3, i get a syntax error, due to the python2 raise statement.

**Comment by robshakir** [comment]
I'll absolutely look at this -- it needs a bit of work since the test framework needs to ensure that both Python 2 and Python 3 work simultaneously.

Pulling the HEAD of the pyang repository - the tool does work with python2:

```
[~/Code/workspace/pyang(master*)]
(20:23 - s001) corretto> head -1 bin/pyang  
#!/usr/bin/env python

[~/Code/workspace/pyang(master*)]
(20:23 - s001) corretto> /usr/bin/env python --version
Python 2.7.6
```

As a temporary workaround until such time as I have managed to look at this, could you use Python 2? I'm happy to review a pull request for this - as long as it covers the test framework too.

**Comment by pbosch** [comment]
I'm not sure how far the work progressed. I was trying to generate code for python 3, but it doesn't do so currently. I only get python 2 syntax. Is it generating code for python 3 implemented or not? And if so, can I enable it somehow?

**Comment by timmartin** [comment]
There's still no support for Python 3, as far as I know. I did some preparatory work a while ago but the first stage is still waiting to be merged (#103). Also issue #104 blocks Python 3, I believe.

**Comment by pbosch** [comment]
Thanks. I was afraid of that. Let's hope it can be resolved.

**Comment by tarkatronic** [comment]
Official Python 3 support has been added to pyangbind with #193.
