### ISSUE TITLE
Issue loading a leaf-list

### ISSUE THREAD

**Issue by lgifre** [robshakir/pyangbind#108]
Hi Rob,

I'm trying to load model data from a string encoded using pyangbind that contains a leaf-list of decimal64 and, generation works properly, but parsing loads empty lists. Let me illustrate the issue with an example.

Given the next model (it contains a list `lis` that has an inner list `values` and the later contains a ```leaf-list``` named as ```coefficients```):
```
module model {
  namespace "urn:upc:model";
  prefix m;

  container con {
    list lis {
      key "name";
      ordered-by system;
      leaf name { type string; mandatory true; }
      list values {
        key "num";
        ordered-by system;
        leaf num { type uint32 { range "0 .. max"; } mandatory true; }
        leaf-list coefficients { type decimal64 { fraction-digits 4; } }
      }
    }
  }
}
```

The Python modules were generated using the next script:
```
export PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
pyang --plugindir $PYBINDPLUGIN -f pybind --use-xpathhelper --split-class-dir m model.yang
```

And I use the next code sniplet to reproduce the issue:
```
import json
from pyangbind.lib import pybindJSON
from pyangbind.lib.pybindJSON import pybindJSONDecoder
from pyangbind.lib.xpathhelper import YANGPathHelper

from m import model
from m.con.lis import lis

l = lis()
l.name = 'item1'

v1 = l.values.add(1)
v1.coefficients.append(7216561431.743998)
v1.coefficients.append(-1018931.4700404946)

v2 = l.values.add(2)
v2.coefficients.append(8216561431.843998)
v2.coefficients.append(-2018931.5700404946)

strData = pybindJSON.dumps(l, mode='default')
elemData = json.loads(strData)
print 'elemData:', elemData

ph = YANGPathHelper()
mdl = model(path_helper=ph)
listObj = ph.get_list('/con/lis')
keyParts = listObj._yang_keys.split(' ')
keyParts = filter(lambda x: len(x) > 0, keyParts)
keyParts = map(lambda x: str(elemData[x]), keyParts)
elemKey = ' '.join(keyParts)
newObj = listObj.add(elemKey)

print 'newObj_before:', pybindJSON.dumps(newObj, mode='default')
pybindJSONDecoder.load_json(elemData, None, None, obj=newObj, path_helper=ph, overwrite=True)
print 'newObj_after:', pybindJSON.dumps(newObj, mode='default')
```

This sniplet creates an item with the described data structure, encodes it as JSON (default mode) and next, it creates a ```YANGPathHelper``` and ```model``` instances to load the generated JSON data.

When you run the code, data labelled as ```elemData``` contains the original JSON data received (it is correct), ```newObj_before``` contains the new object added to the model data structure (only with the key, it is fine), and ```newObj_after``` contains the new object after loading all the values (it is partially loaded because ```leaf-list``` entities are not loaded).
Note that I added the ```overwrite=True``` in the ```load_json``` method.

Could you take a look on it and check if I'm doing something in the wrong way?
TIA,
Lluís

**Comment by robshakir** [comment]
Hi Lluis,

Interesting - I added test cases for this after validating a decimal fix. Can you check with the current HEAD of master? [Will merge in the next couple of mins if CI succeeds.]

Thanks.
r

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity
