### ISSUE TITLE
openconfig-rib-bgp.yang creates bgp_rib folder. It should be rib_bgp

### ISSUE THREAD

**Issue by vnitinv** [robshakir/pyangbind#112]
pyang --plugindir $PYBINDPLUGIN -f pybind --split-class-dir /var/tmp/openconfig openconfig-rib-bgp.yang

$ ls
__init__.py	__init__.pyc	bgp		bgp_rib

I think folder created should be rib_bgp (in-line to file and module name rib_bgp) and not bgp_rib.

**Comment by robshakir** [comment]
Per #113, this is the expected behaviour. Please re-open #113 if this needs additional clarification.
