### ISSUE TITLE
module openconfig-vlan creates vlans folder

### ISSUE THREAD

**Issue by vnitinv** [robshakir/pyangbind#113]
nitinkr-mba13:yang nitinkr$ pyang --plugindir $PYBINDPLUGIN -f pybind --split-class-dir /var/tmp/openconfig openconfig-vlan.yang 
nitinkr-mba13:yang nitinkr$ cd /var/tmp/openconfig/
nitinkr-mba13:openconfig nitinkr$ ls
__init__.py	__init__.pyc	bgp		bgp_rib		vlans

$ more openconfig-vlan.yang 
module openconfig-vlan {

Should it create vlan or vlans folder

**Comment by robshakir** [comment]
I'm not sure what the issue that is being reported here is. The output of pyangbind will be a class definition called `openconfig_vlan` which is defined in the `__init__.py` file. The folders that are then created correspond to the schematree paths - so `vlans` in the case of `openconfig-vlan` as this is the top-level container that is created.

r.

**Comment by robshakir** [comment]
Please re-open this issue if further clarification is required.
