### ISSUE TITLE
Generating a Set of Classes

### ISSUE THREAD

**Issue by pyman007** [robshakir/pyangbind#115]
I am getting following error, can you please help?

bash-3.2$ $PYBINDPLUGIN
bash: /usr/local/lib/python3.5/site-packages/pyangbind/plugin: is a directory
bash-3.2$
bash-3.2$ SDIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash-3.2$ PYBINDPLUGIN=`/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'`
bash-3.2$ pyang --plugindir $PYBINDPLUGIN -f pybind -o $SDIR/sbindings.py simple_serialise.yang
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 434, in <module>
    run()
  File "/usr/local/bin/pyang", line 30, in run
    plugin.init(plugindirs)
  File "/usr/local/lib/python3.5/site-packages/pyang/plugin.py", line 37, in init
    pluginmod = __import__(fname[:-3])
  File "/Library/Python/2.7/site-packages/pyangbind/plugin/pybind.py", line 303
    print "INFO: encountered %s" % str(e)
                               ^
SyntaxError: invalid syntax
bash-3.2$

**Comment by robshakir** [comment]
Currently, pyangbind doesn't support Python 3, you'll need to run this command using a Python 2.7 interpreter (it looks like you're running it with Python 3.5).

Thanks,
r.
