### ISSUE TITLE
`_changed` left as `False` when leaf is set to it's default value

### ISSUE THREAD

**Issue by dbarrosop** [robshakir/pyangbind#120]
Hello,
apparently, if you set an attribute to it's default, `_changed` is left unmodified. What's the rationale behind that behavior? Is there any way to know the user set the value in that case? It would be interesting to have `get(filter=True)`(or some other argument) return any value the user might have tried to set even if it was the default value.

Thanks
David

**Comment by robshakir** [comment]
Hey David,

Sorry I missed this. `_changed` essentially was designed to be able to track what leaves would need to be serialised, and similar to the NETCONF `trim` behaviour (see RFC6243) then it doesn't serialise defaults. The idea was to ensure that the minimum output possible is produced when the user does a `.get()` such that elements that are specified in the schema with the same value are specified.

At the moment, it isn't possible to know that something has changed when it is set to the default. A fix for this would be for us to change the `_changed` behaviour to set to true if the value was changed at all, and then have the `.get()` implementation filter this out. We'd probably want to have some new argument that would allow the different modes that we might want. I'd propose to leave `filter=True` doing the same thing as it does today, but then have a `any_change=True` for the mode you suggest. We could also have a `with_defaults` flag which allows any leaf with a default to be serialised.

Any thoughts?

r.

**Comment by dbarrosop** [comment]
> I'd propose to leave filter=True doing the same thing as it does today, but then have a any_change=True for the mode you suggest

I agree, I think that is the best option. I couldn't find an easy way of implementing it when I looked into this (still not too familiar with the code) so I hacked it by just doing in my code:

```
my_obj.attr = "blah"
my_obj.attr._mchanged = True
```

I know, I know... :P If you don't have the time to fix this let me know and I will take a look again (pointers are welcome as last time I failed to see how to implement this).

**Comment by robshakir** [comment]
Hey David,

Sure - let me take a look at this and push something you can test.

Cheers,
r.

**Comment by dbarrosop** [comment]
Did you get the chance to work on this?

Thanks!

**Comment by tarkatronic** [comment]
Fixed via #203
