### ISSUE TITLE
Netconf XML requests using pyangbind Class

### ISSUE THREAD

**Issue by parkrish** [robshakir/pyangbind#122]
Hi,

As an experiment, I attempted integrating  ncclient, a python based Netconf client with the pyangbind.
With this on set/get operation of the pyangbind auto-generated class objects, I was able to generate its equivalent edit-config/get Netconf XML messages. 

As you know, the Netconf protocol allows multiple yang objects to be configured with a single edit-config message.The same was taken into consideration. So multiple pyangbind generated yang objects can be set before generating a Netconf edit-config message for them.

My development involved writing a new class called pybindXMLEncoder to generate the XML based Netconf message.The same will be fed to the ncclient APIs to send the required Netconf message.

I also did minor additions to the pybind.py.This was needed to keep track of the list of objects user is setting through set operation before generating the edit-config message.

I feel that this can be useful to the community. if you think this will be of use or if you think you need to know more on the changes I can write to you in mail with details of my changes.

Thanks and regards,
Parameswaran Krishnamurthy

**Comment by robshakir** [comment]
Hi Parameswaran!

Thanks very much for sharing this, it's great to hear that you're working through using pyangbind to help with this. We've previously had some requests for XML serialisation support in pyangbind (see #36). If you would perhaps consider making a contribution of the pybindXMLEncoder class, then we'd be more than grateful to helpe integrate it.

Additionally, I'd be very interested to see the changes to look at the set of objects that are being modified by the user, we have the `changed()` method right now, but if there's something in addition it'd be great to review it.

If you're having any difficulty submitting to GitHub, please do let me know.  If you'd rather do this via email, please do email me at robjs@google.com.

Thanks!
r.

**Comment by sdcrooks** [comment]
Rob / Parameswaran,

I am interested in possibly using pyangbind but also require XML serialization. Just wondering what the status of Parameswaran's update is - it sounds as though it would quite useful.

Regards,

Steve

**Comment by robshakir** [comment]
Hi Steve,

Parameswaran and I discussed via email -- he was just going to examine whether the terms of the CLA for contributions were acceptable to his employer, such that we could review this contribution.

Thanks,
r.

**Comment by sdcrooks** [comment]
Rob,

Thank you for the prompt response.
I'll start experimenting with pyangbind and hopefully Parameswaran will be able to contribute his changes.

Regards,
Steve

**Comment by parkrish** [comment]
Hi,

Sorry for the delay from my end.I'm awaiting response from our legal team.
I shall followup and try to close this soon.

Best regards,
Parameswaran

**Comment by kb3ien** [comment]
Parameswaran, I am also looking forward to the release of XML support,

Robin

**Comment by wisotzky** [comment]
@parkrish, Any updates?
/Sven

**Comment by robshakir** [comment]
Unfortunately, it looks like the original PR author was unable to submit their changes as a PR. However, @unsignedint has now implemented this -- thanks, and I'm sure the folks in this issue will also be interested. Closing the issue :-)
