### ISSUE TITLE
Fail to generate bindings for ietf-netconf-monitoring: FATAL: unmapped type (instance-identifier)

### ISSUE THREAD

**Issue by mathieu-mercier** [robshakir/pyangbind#123]
When parsing the YANG model ietf-netconf-monitoring obtained from http://www.netconfcentral.org/modulereport/ietf-netconf-monitoring a leaf-list using the built-in type instance-identifier causes an error:
# pyang --plugindir $PYBINDPLUGIN -f pybind -o binding.py ietf-netconf-monitoring.yang
FATAL: unmapped type (instance-identifier)
[ u'inet:dscp',
  u'ncm:netconf-soap-over-beep',
  u'xpath1.0',
  u'netconf-soap-over-beep',
  'boolean',
  u'inet:domain-name',
  u'yang-identifier',
  u'object-identifier-128',
  u'inet:uri',
  u'yang:gauge32',
  u'yang:phys-address',
  u'yang:xpath1.0',
  u'inet:ipv4-address-no-zone',
  u'yang:counter32',
  u'uuid',
  u'ncm:yang',
  u'hex-string',
  u'ncm:xsd',
  u'yin',
  u'yang:counter64',
  'uint16',
  u'zero-based-counter64',
  u'netconf-soap-over-https',
  u'gauge64',
  u'mac-address',
  'empty',
  'int32',
  u'inet:ipv6-address-no-zone',
  u'date-and-time',
  'string',
  u'rnc',
  u'timestamp',
  u'rng',
  'uint8',
  u'ipv6-prefix',
  u'yang:yang-identifier',
  u'ncm:netconf-datastore-type',
  u'yang:hex-string',
  u'ncm:netconf-tls',
  'int8',
  'uint64',
  u'inet:ip-version',
  u'phys-address',
  'decimal64',
  u'domain-name',
  u'ncm:netconf-beep',
  u'xsd',
  u'ip-prefix',
  u'inet:ipv6-prefix',
  u'netconf-beep',
  u'ncm:schema-format',
  u'counter64',
  u'netconf-ssh',
  u'yang:uuid',
  u'timeticks',
  u'uri',
  u'netconf-tls',
  u'host',
  u'zero-based-counter32',
  u'inet:ip-prefix',
  u'ipv6-address-no-zone',
  u'ipv4-address',
  u'transport',
  'binary',
  u'yang:dotted-quad',
  u'dotted-quad',
  u'yang:mac-address',
  u'inet:as-number',
  u'as-number',
  u'yang:object-identifier-128',
  u'ipv4-address-no-zone',
  u'ip-version',
  u'counter32',
  u'inet:ipv6-address',
  u'inet:ip-address-no-zone',
  'uint32',
  u'ncm:rng',
  u'ipv4-prefix',
  'int16',
  u'ncm:rnc',
  u'dscp',
  u'ncm:netconf-ssh',
  u'port-number',
  u'ncm:transport',
  u'yang:object-identifier',
  u'inet:ipv4-prefix',
  u'schema-format',
  u'yang:zero-based-counter64',
  u'object-identifier',
  u'inet:ip-address',
  u'inet:host',
  u'ip-address-no-zone',
  u'yang:zero-based-counter32',
  u'ncm:yin',
  u'yang:date-and-time',
  u'yang:timestamp',
  u'yang:timeticks',
  u'yang:gauge64',
  u'ipv6-flow-label',
  u'inet:ipv6-flow-label',
  u'netconf-datastore-type',
  u'yang',
  'int64',
  u'gauge32',
  u'ipv6-address',
  u'inet:port-number',
  u'ip-address',
  u'inet:ipv4-address',
  u'ncm:netconf-soap-over-https']
u'instance-identifier'
False

I tried both with the release 0.5.11 and the current master branch.

**Comment by robshakir** [comment]
Hi,

Currently, pyangbind doesn't map instance-identifier to any particular type. Could you explain what behaviour you would expect here, such that this is something that could be scoped? I'm happy to review a patch for this work.

Thanks,
r.

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity
