### ISSUE TITLE
JSONXSL plugin needs a valid module

### ISSUE THREAD

**Issue by sidheshdivekar29** [robshakir/pyangbind#143]
Hi,
Am trying to get json from openconfig-bgp and seeing "JSONXSL plugin needs a valid module" error
with "-f jsonxsl" argument.
Its able to create tree without any issue.

~/workspace/public/release/models/bgp$ pyang -f tree -p openconfig-bgp.yang openconfig-bgp-types.yang openconfig-bgp-policy.yang openconfig-bgp-peer-group.yang openconfig-bgp-neighbor.yang openconfig-bgp-global.yang openconfig-bgp-errors.yang openconfig-bgp-common.yang openconfig-bgp-common-structure.yang openconfig-bgp-common-multiprotocol.yang openconfig-extensions.yang openconfig-routing-policy.yang openconfig-yang-types.yang openconfig-policy-types.yang openconfig-types.yang openconfig-inet-types.yang openconfig-interfaces.yang -o tree.txt
~/workspace/public/release/models/bgp$ 

~/workspace/public/release/models/bgp$ pyang -f jsonxsl -p openconfig-bgp.yang openconfig-bgp-types.yang openconfig-bgp-policy.yang openconfig-bgp-peer-group.yang openconfig-bgp-neighbor.yang openconfig-bgp-global.yang openconfig-bgp-errors.yang openconfig-bgp-common.yang openconfig-bgp-common-structure.yang openconfig-bgp-common-multiprotocol.yang openconfig-extensions.yang openconfig-routing-policy.yang openconfig-yang-types.yang openconfig-policy-types.yang openconfig-types.yang openconfig-inet-types.yang openconfig-interfaces.yang
JSONXSL plugin needs a valid module

**Comment by robshakir** [comment]
Please file this bug against pyang, rather than pyangbind. Anything that isn't `-f pybind` isn't something that runs pyangbind code!

Thanks,
r.
