### ISSUE TITLE
No support for complex ranges

### ISSUE THREAD

**Issue by marksutherland** [robshakir/pyangbind#15]
RFC 6020 allows ranges to be discontinuous, using the | to separate each sub-range, as long as the range delimiters increase from left to right. For example the following is allowed:

```
type int8 {
    range "-10 .. -5 | 5 .. 10 | 20 .. 30"
}
```
See section 9.2.4 for details: https://tools.ietf.org/html/rfc6020#section-9.2.4
This also seems to apply to string lengths: https://tools.ietf.org/html/rfc6020#section-9.4.4

If such a range exists in an input yang file, the follow error occurs:

```
  File "/home/msuther/Repositories/pyangbind/lib/yangtypes.py", line 839, in YANGDynClass
    return YANGBaseClass(*args, **kwargs)
  File "/home/msuther/Repositories/pyangbind/lib/yangtypes.py", line 717, in __init__
    raise TypeError, "couldn't generate dynamic type -> %s -> %s" % (type(e),e)
TypeError: couldn't generate dynamic type -> <type 'exceptions.ValueError'> -> too many values to unpack
```

**Comment by robshakir** [comment]
Hi Mark,

Thanks for reporting this -- can you check the master branch now and see whether this works for you. I didn't add the sanity checking as to whether the ranges should increase, as pyang should validate against 6020 rules - but the multiple ranges are now supported as of 187d0cb6c1255dcf10b7191c0bfd3a1df093de5c.

Cheers,
r.

**Comment by marksutherland** [comment]
Hi,

Thanks for the quick response! Seems to work for positive ranges, but doesn't when negative numbers are involed. Here are some failing examples:

```
leaf intLeafWithRange {
        type int8 {
                range "-10 .. -5 | 10 .. 30";
        }
}
leaf dec64LeafWithRange {
        type decimal64 {
                fraction-digits 6;
                range "-333.33 .. -222.22 | 111.1 | 444.444 .. 555.555";
        }
}
```

Mark

**Comment by robshakir** [comment]
Hi Mark,

No worries -- there were a couple of issues with one of my test cases, and then some things were not supported (as you'd spotted, I'd missed the negative value case, and the equality case was not supported either).

Please see the latest commit in master. I've used your test cases in the tests too.

**Comment by marksutherland** [comment]
Hi Rob,

That seems to be working now! Thanks!

Mark

**Comment by robshakir** [comment]
No problems.

**Comment by marksutherland** [comment]
Hi, I just tried out a complex string length and get the same result as above. From the descriptions of range and length in the RFC, it looks like they are the same restriction with a different name, so they should be parsed the same way.

```
leaf stringLeafWithComplexLength {
        type string {
                length "1 .. 20 | 30 .. 40";
        }
}
```

results in this on instantiation:

```
  File "/home/msuther/Repositories/pyangbind/lib/yangtypes.py", line 876, in YANGDynClass
    return YANGBaseClass(*args, **kwargs)
  File "/home/msuther/Repositories/pyangbind/lib/yangtypes.py", line 754, in __init__
    raise TypeError, "couldn't generate dynamic type -> %s -> %s" % (type(e),e)
TypeError: couldn't generate dynamic type -> <type 'exceptions.ValueError'> -> too many values to unpack
```

**Comment by robshakir** [comment]
@marksutherland 

Hi Mark,

Apologies, missed this issue with the Thanksgiving break -- please see changes in ed2c2b156b78ff9b0296bfe13db36aa5fda384cc which do as you suggest and add the same semantics to length as are implemented for range.

Any issues please re-open this issue.

Cheers,
r.

**Comment by marksutherland** [comment]
Hi @robshakir,

Thanks! I’ve verified that it works with the yang I was using as well. Hope
you had a nice break!
