### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by madhurabhogate** [robshakir/pyangbind#154]
Is this library not python 3 compatible ?

**Comment by robshakir** [comment]
Currently, pyangbind isn't compatible with python3. There is some work in https://github.com/robshakir/pyangbind/compare/master...AdamIsrael:master that you can look at for some support, but this isn't something that is yet supported in master of this repo.

**Comment by madhurabhogate** [comment]
Thank you @robshakir . Do you have any plans to have this support in the master sooner ?

**Comment by tarkatronic** [comment]
@madhurabhogate I have been actively working toward Python 3 compatibility, but it is slightly delayed, as I am working on improving the test suite first. I want to be able to prove thorough test coverage of the library before I begin a full effort toward a change of this size.

That said, the test conversion is around half complete, if not more, and the test coverage is looking very promising. With that, I have started a more thorough analysis of the code and begun some of the work toward Python 3 compatibility in parallel with the latter part of the tests.

**Comment by tarkatronic** [comment]
@madhurabhogate Can you try the latest version from git? I have Python 3 support tentatively working, but would love to get more real world test results.

Note that there is no official release yet, as of the time I am writing this, with Python 3 support; it is only in git so far.

**Comment by tarkatronic** [comment]
Closing this ticket, as python 3 support has been officially released now.
