### ISSUE TITLE
CLI command for pyangbind not found after pip install

### ISSUE THREAD

**Issue by Mazimer** [robshakir/pyangbind#157]
I've installed pyangbind with pip3 install pyangbind after which, as i understand it, a shell command should be available. The problem is, that command is simply not showing up and googling has not yielded anyone else having a similar issue.

i'm running a clean install of kubuntu 17.10 VM on a Windows host.

any help would be appreciated.

**Comment by mike-albano** [comment]
You don't run pyangbind directly; it's passed as a plugin to pyang.
See the readme; specifically: https://github.com/robshakir/pyangbind#generating-a-set-of-classes-
