### ISSUE TITLE
Transition Unit Tests to unittest.

### ISSUE THREAD

**Issue by robshakir** [robshakir/pyangbind#164]
This issue tracks the work that @tarkatronic kicked off to refactor testing to use `unittest` rather than the custom approach we had before:

Status:
* [X] binary
* [X] boolean-empty
* [X] choice
* [x] config-false
* [x] decimal64
* [x] enumeration
* [x] extensions
* [x] extmethods
* [x] identityref
* [x] include-import
* [x] int
* [x] integration
  * [x] openconfig-bgp
  * [x] openconfig-interfaces
* [x] leaf-list
* [x] list
* [x] misc
* [x] nested-containers
* [x] notification
* [x] openconfig-bgp-juniper
* [x] presence
* [x] rpc
* [x] serialise
  * [x] ietf-json-deserialise
  * [x] ietf-json-serialise
  * [x] json-deserialise
  * [x] json-serialise
  * [x] juniper-json-examples
  * [x] openconfig-serialise
* [x] split-classes
* [x] string
* [x] submodules
* [X] typedef
* [x] uint
* [x] union
* [x] xpath
  * [x] 00_pathhelper_base
  * [x] 01-list_leaflist
  * [X] 02-static_ptr
  * [X] 03-current
  * [X] 04-root

**Comment by tarkatronic** [comment]
![](https://media.giphy.com/media/3oKIPf3C7HqqYBVcCk/giphy.gif)
