### ISSUE TITLE
Fields which share the name of python keywords cause issues

### ISSUE THREAD

**Issue by marksutherland** [robshakir/pyangbind#17]
I just tried to generate bindings for some modules, one of which happens to have a 'continue' field. When you try to use the binding, python gets very confused:

```
  File "/home/msuther/Repositories/netconf-utils/bindings.py", line 5106
    continue = property(_get_continue, _set_continue)
             ^
SyntaxError: invalid syntax
```

I suspect this will probably happen for most python built-ins.

**Comment by robshakir** [comment]
These need to be added to lib/yangtypes.py - line 34, there is a list called "reserved_name" that handles this case. Please let me know any others that are not in this list.

**Comment by marksutherland** [comment]
Ah, cool. I suspect anything in here in ''s probably needs to be added to the list:
https://docs.python.org/2/reference/grammar.html

**Comment by marksutherland** [comment]
See #18 for the outstanding keywords from 2.7. The same thing probably needs to be done for 3, but judging by #10 that's not essential yet.

**Comment by robshakir** [comment]
Thanks!

Yes, there is no support for Python 3 in pyangbind yet. I made some of the changes mentioned in #10, but saw no further requests. I'd like some more support for this being a requirement before doing the work to update. Our applications currently are not written in Python 3.
