### ISSUE TITLE
Unify/update the documentation

### ISSUE THREAD

**Issue by tarkatronic** [robshakir/pyangbind#198]
The current documentation is somewhat fragmented, and becoming outdated. I think the best option for uplifting it, as opposed to continuing to grow an already large README, will be to use Read The Docs, utilizing their auto deployments.

**Comment by tarkatronic** [comment]
After speaking with Rob, another option is to find a way to maintain https://github.com/robshakir/pynms/tree/gh-pages-gen/source

These are GitHub pages, deployed to http://pynms.io/pyangbind/.

Those appear to be mostly copy-pasta from the docs folder in this repo, so some form of unification of these efforts needs to happen.

**Comment by JoseIgnacioTamayo** [comment]
Documentation at https://github.com/robshakir/pyangbind/tree/master/docs, also at the main README.md. A smaller doc is in README.srt and copied to https://pypi.org/project/pyangbind/
