### ISSUE TITLE
pyang bind fails for identityref - openconfig

### ISSUE THREAD

**Issue by nkaliape** [robshakir/pyangbind#199]
related: https://github.com/robshakir/pyangbind/issues/8

Goal:
Get the XML payload
Convert the XML payload to JSON - for pybind (using xsltproc)
Feed JSON to create python objects
Modify objects as necessary and create back payload for netconf

Issue:
When JSON fed to python object - fails on "identityref"
Please suggest a solution.
```xml
(testenv) nkaliape@narayan-vm:/tmp$ cat fail_xslt_iana.xml
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <interfaces xmlns="http://openconfig.net/yang/interfaces">
            <interface>
                <name>eth1/1</name>
                <config>
                    <description>SE1</description>
                    <enabled>false</enabled>
                    <name>eth1/1</name>
                    <mtu>1500</mtu>
                    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
                </config>
            </interface>
        </interfaces>
    </data>
```
Note: XSL file is created using pyang API: 
```sh
xsltproc -o /tmp/fail_xslt_iana.json openconfig-interfaces.xsl /tmp/fail_xslt_iana.xml
```
```json
(testenv) nkaliape@narayan-vm:/tmp$ cat fail_xslt_iana.json 
{
  "openconfig-interfaces:interfaces": {
    "interface": [
      {
        "name": "eth1/1",
        "config": {
          "description": "SE1",
          "enabled": false,
          "name": "eth1/1",
          "mtu": 1500,
          "type": "iana-if-type:ethernetCsmacd"
        }
      }
    ]
  }
}
```
When Translated field is fed - it is causing this issue.
```python
<snip>    
>>> i.interfaces.interface['eth0'].config._set_type('iana-if-type:ethernetCsmacd') ## Fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openconfig_interfaces.py", line 244, in _set_type
    g:iana-if-type', u'@module': u'iana-if-type'}, u'ianaift:hippiInterface': {u'@namespace': u'urn:ietf:params:xml:ns:yang:iana-if-type', u'@module': u'iana-if-type'},
<snip>    
ValueError: {'error-string': 'type must be of a type compatible with identityref',
```

Thanks,
Narayan

**Comment by tarkatronic** [comment]
@nkaliape What YANG models are you using, and what `pyang` command did you use to invoke `pyangbind`?

**Comment by nkaliape** [comment]
PYBINDPLUGIN=/home/nkaliape/testenv/local/lib/python2.7/site-packages/pyangbind/plugin
# creates pybind
pyang --lax-quote-checks --plugindir $PYBINDPLUGIN -f  pybind -o openconfig_interfaces.py openconfig-interfaces.yang openconfig-if-aggregate.yang openconfig-if-ethernet.yang openconfig-if-ip-ext.yang openconfig-if-ip.yang openconfig-vlan.yang iana-if-type.yang
# creates jtox
pyang --lax-quote-checks --plugindir $PYBINDPLUGIN -f  jtox -o openconfig-interfaces.jtox openconfig-interfaces.yang openconfig-if-aggregate.yang openconfig-if-ethernet.yang openconfig-if-ip-ext.yang openconfig-if-ip.yang openconfig-vlan.yang iana-if-type.yang
# creates xsl
 pyang --lax-quote-checks --plugindir $PYBINDPLUGIN -f  jsonxsl -o openconfig-interfaces.xsl openconfig-interfaces.yang openconfig-if-aggregate.yang openconfig-if-ethernet.yang openconfig-if-ip-ext.yang openconfig-if-ip.yang openconfig-vlan.yang iana-if-type.yang

feed XML payload to xsltproc to create JSON
Feed JSON to pybind using:
obj = pbJ.load_ietf(json_file, bindings_class, oc_name)

Here oc_name is "openconfig-interfaces".
bindings_class is "openconfig_interfaces"
