### ISSUE TITLE
XML support for serialization

### ISSUE THREAD

**Issue by rsterkendries** [robshakir/pyangbind#206]
I can read from the doc that XML is not supported as a serialization format.
[https://github.com/robshakir/pyangbind#serialising-a-data-instance-](https://github.com/robshakir/pyangbind#serialising-a-data-instance-)
--> "XML - the rules for this mapping are defined in RFC 7950 - **currently NOT SUPPORTED**."

Is it foreseen? Is there anyone working on it already or interested in developing it?

Also is it worth it? I have no idea of the ratio of devices supporting XML/JSON today.

Regards,
Roland

**Comment by tarkatronic** [comment]
Hi @rsterkendries,

There is no active work on this feature today to my knowledge. That said, if this is a feature you would like to see, contributions are very welcome!

As to being worth it, I can not speak to the support ratio either, so I think the value may come down to your own use case.

**Comment by robshakir** [comment]
We started writing XML support a while back, see [this commit](https://github.com/robshakir/pyangbind/commit/6a02282b26de63abba614e936146cb1f513d2ca1). Later, in #122 I think there was a contribution, but we couldn't work out the CLA issues.

A number of devices support XML encoding, but with the advent of RESTCONF, RFC7951 JSON is becoming much more widely supported. It's up to your situation, as Joey says, as to whether this is worth it.

**Comment by robshakir** [comment]
Thanks to the great work @unsignedint has done, this is now implemented in pyangbind. Closing the issue!
