### ISSUE TITLE
JSON IETF serialization not using namespace prefix (fails IETF deserialization)

### ISSUE THREAD

**Issue by markuscraig** [robshakir/pyangbind#207]
I'm generating OpenConfig wifi python code with pyang like this...

```
$ pyang --plugindir /Users/mark/go/src/github.com/mistsys/demoapi/venv/lib/python2.7/site-packages/pyangbind/plugin -f pybind --path /tmp/openconfig_public/release/models --build-notifications -o /Users/mark/go/src/github.com/mistsys/demoapi/demoapi/openconfig/models/openconfig_access_points.py /tmp/openconfig_public/release/models/wifi/access-points/openconfig-access-points.yang
```

For any property of a 'openconfig-wifi-type' (ie: 'FREQ_2GHZ'), the generated restrictions use the yang 'oc-wifi-prefix' located in 'openconfig-wifi-types' (looks good to me).

However, when using `pybindJSON.dumps` to serialize in `ietf` mode, the generated JSON uses the defining module as the namespace (ie: `openconfig-wifi-types:FREQ_2GHZ`) rather than the yang model prefix (ie: `oc-wifi-types:FREQ_2GH`)...

```
$ aps = openconfig_access_points()
$ oc_ap = aps.access_points.access_point.add(hostname)
$ radio = oc_ap.radios.radio.add(0)
$ radio.config.operating_frequency = 'FREQ_5GHZ'
$ pybindJSON.dumps(oc_aps, mode='ietf', indent=None)
```

The net result is that I'm seeing an error when deserializing the JSON IETF string that was generated with `pybindJSON.dumps`...

```
            # deserialize the json-ietf data
            aps = openconfig_access_points()
            d = json.loads(json_ietf)
            pybindJSONDecoder.load_ietf_json(d, None, None, obj=aps)
```

Here is the error where the `openconfig-wifi-types:FREQ_2GHZ` type is not within the restricted list generated by pyang (ie: needs to be `oc-wifi-types:FREQ_2GHZ` using the `oc-wifi-type` namespace prefix)...

```
  File "/Users/mark/go/src/github.com/mistsys/demoapi/demoapi/openconfig/models/openconfig_access_points.py", line 152, in _set_operating_frequency
    'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_type="dict_key", restriction_arg={u'oc-wifi-types:FREQ_2GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}, u'oc-wifi-types:FREQ_5GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}, u'oc-wifi-types:FREQ_2_5_GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}, u'FREQ_5GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}, u'FREQ_2_5_GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}, u'FREQ_2GHZ': {u'@namespace': u'http://openconfig.net/yang/wifi/types', u'@module': u'openconfig-wifi-types'}},), is_leaf=True, yang_name="operating-frequency", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/wifi/access-points', defining_module='openconfig-access-points', yang_type='identityref', is_config=True)""",
ValueError: {'error-string': 'operating_frequency must be of a type compatible with identityref', 'generated-type': 'YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_type="dict_key", restriction_arg={u\'oc-wifi-types:FREQ_2GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}, u\'oc-wifi-types:FREQ_5GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}, u\'oc-wifi-types:FREQ_2_5_GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}, u\'FREQ_5GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}, u\'FREQ_2_5_GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}, u\'FREQ_2GHZ\': {u\'@namespace\': u\'http://openconfig.net/yang/wifi/types\', u\'@module\': u\'openconfig-wifi-types\'}},), is_leaf=True, yang_name="operating-frequency", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace=\'http://openconfig.net/yang/wifi/access-points\', defining_module=\'openconfig-access-points\', yang_type=\'identityref\', is_config=True)', 'defined-type': 'openconfig-access-points:identityref'}
```

It seems like this code always uses the defining module rather than the namespace prefix of the type...

https://github.com/robshakir/pyangbind/blob/master/pyangbind/lib/serialise.py#L545-L548

Hopefully, I'm missing something basic, thanks!

**Comment by markuscraig** [comment]
Hmmm, I'm starting to think that this is a `pyang` bug (not `pyangbind`).

I believe that JSON IETF is supposed to use the module-name as a prefix (ie: 'openconfig-wifi-types') instead of the module prefix (ie: 'oc-wifi-types').

What do you all think?

**Comment by robshakir** [comment]
RFC 7951 JSON should use the module name as the prefix, *not* the `prefix` specified in the YANG. The relevant part of the spec is in [Section 4](https://tools.ietf.org/html/rfc7951#section-4) of the doc:

```
   o  namespace-qualified - the data node identifier is prefixed with
      the name of the module in which the data node is defined,
      separated from the data node identifier by the colon character
      (":").
```

`ygot` and `pyangbind` do the same thing here and use the module name. 

There does appear to be an issue here though, since AIUI, you can't use `load_json_ietf` when the output is from `dumps`. That's definitely not good.

**Comment by robshakir** [comment]
Looks like a dup of #199. Verifying why we don't have test coverage here :-(

**Comment by robshakir** [comment]
PR #209 should fix this issue.

When we resolve identities internally, we store the `prefix`-prefixed version and the plain string, but not the module name prefixed. This meant that where an identityref ended up being prefixed (only required when the `identity` is defined outside of the current module), then we didn't have the right lookup key to figure it was a valid value.

PR re-works this by stripping the prefix if it's encountered. PTAL.

**Comment by markuscraig** [comment]
Awesome, thanks @robshakir for great explanation, sounds good!
