### ISSUE TITLE
Containers with "config false" in YANG are created as "config=True" in Python

### ISSUE THREAD

**Issue by nicolasmorini** [robshakir/pyangbind#221]
Given the following YANG module:

```
module my-module {
    container my-container {
        config false;
        container my-nested-container {
            leaf my-leaf {
                type uint8;
            }
        }
    }
}
```

The Python definition of `my-container` has `is_config=True` in its `__init__` method, which is wrong. Nevertheless, `my-nested-container` is correctly defined as `is_config=False`.

By digging in the code, I found that containers are ALWAYS defined as configurable except when nested in a non-configurable container. In other words, pyangbind ignores the YANG `config` statement and defaults to `True`, but it successfully inherits the configurable attribute from parents.

I have a pull request with a proposed fix (#222)

Cheers!
Nicolas

Small disclaimer: I'm fairly new to NETCONF/YANG, so if I am getting anything wrong here, please let me know. This is also my first contribution to a GitHub project so, please let me know if the issue/pull-request methodology is somehow wrong.

**Comment by xavier-contreras** [comment]
This was fixed in https://github.com/robshakir/pyangbind/pull/323
