### ISSUE TITLE
No support for two primary keys in a list

### ISSUE THREAD

**Issue by z-peter** [robshakir/pyangbind#230]
Have the follow yang model, which is successfully built:
module lan5-l3-uc {
  namespace "xxxx";
  prefix lan5-l3-uc;

  import ietf-inet-types {
    prefix inet;
  }

  import lan5-l1 {
    prefix lan5-l1;
  }

    list lan5-l3-uc-service {

      key "sp-name service-type";

      leaf sp-name {
        description "The name of the service provider (lower case and numbers)";
        type string {
          pattern "[0-9a-z]*";
        }
        mandatory true;
      }
      
      leaf service-type {
        description "Controls QoS";
        type enumeration {
          enum bb {
            value 1;
          }
          enum voip {
            value 2;
          }
          enum iptv {
            value 3;
          }
          enum cgnatbb {
            value 4;
          }
        }
        mandatory true;
      }
..... more entries but omitted for simplicity

pyang -f tree lan5-l3-uc.yang 
module: lan5-l3-uc
  +--rw lan5-l3-uc-service* [sp-name service-type]
     +--rw sp-name                   string
     +--rw spid                      uint32
     +--rw service-type              enumeration

Running python interpreter:
>>> a = binding_lan5_l3_uc.lan5_l3_uc()
>>> a.lan5_l3_uc_service.add(["alltele" "bb"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyangbind/lib/yangtypes.py", line 755, in add
    if k in self._members:
TypeError: unhashable type: 'list'
>>> 

From above it seems like multiple primary keys are not supported. Any plans implement support for multiple primary keys.

**Comment by chrisy** [comment]
In my experience compound keys work fine with pyangbind, but you can't index them with an iterable; you compound the keys into a single string, eg in your case, `a.lan5_l3_uc_service.add("alltele bb")`

**Comment by chrisy** [comment]
Being able to use an iterable as the key, though, would provide for more precision, eg if a value needed to contain a space. There may be an equivalent way to do this but I have not yet stumbled across it!

**Comment by z-peter** [comment]
Thanks chrisy, works very well!
I prefer not to use space in my keys so no issue for me.

**Comment by robshakir** [comment]
There are also mechanisms in the generated code to specify the keys by name. The handling code [here](https://github.com/robshakir/pyangbind/blob/master/pyangbind/lib/yangtypes.py#L759) means that if you specify `list.add(key1="val one", key2="val 2")` where `key1` and `key2` are the YANG names of the keys, then this will be cleanly handled in the `add`.  `_item` will then allow retrieval using the same logic.
