### ISSUE TITLE
Wrong parsing of two nested empty presence containers

### ISSUE THREAD

**Issue by jonasglass** [robshakir/pyangbind#239]
Hi Rob,

I´ve seen that you already had discussions regarding empty presence containers. I think it is fine to just create empty classes for them as you are doing it right now.

However it looks like it is not considered if there is another presence container inside another one, this is possible using augmentation. Following you can see the tree structure of a test setup to reproduce this issue. You will find the YANG files as well as the generated binding attached to this issue.

>module: test-module
>  +--rw root
>     +--rw capabilities!

>module: test-module-extended
>  augment /tm:root/tm:capabilities:
>    +--rw capability-a!

Spoiler: The generated classes do contain `root `and `capabilities`. The container `capabilities `however is empty and does not contain an empty class `capability-a` as I would expect it to.

[binding-test.zip](https://github.com/robshakir/pyangbind/files/2801924/binding-test.zip)

**Comment by JoseIgnacioTamayo** [comment]
This was fixed in https://github.com/robshakir/pyangbind/issues/336
