### ISSUE TITLE
pybindIETFXMLEncoder.encode serialization issue

### ISSUE THREAD

**Issue by agunturu** [robshakir/pyangbind#242]
When the python yang object is serialized to XML, the key elements of the list must appear first (https://tools.ietf.org/html/rfc7950#page-88). But the output is just following the order in the yang file.

For example, consider the following yang:
list foo {
    key "idx";
    description
      "Standalone config stuff";
    leaf f1 {
      type uint32;
      description
        "List key";
    }
    leaf idx {
      type uint32;
      description
        "List key";
    }
  }

The output xml should be:
``
    <foo>
        <idx>0</idx>
        <f1>1</f1>
    </foo>
``

But currently you get:
``
    <foo>
        <f1>1</f1>
        <idx>0</idx>
    </foo>
``

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing issue without recent updates.
