### ISSUE TITLE
pyangbind from pip (PyPi) and GitHub are different!

### ISSUE THREAD

**Issue by tonic12** [robshakir/pyangbind#249]
I'm compare pyangbind from PyPi and GitHub and it's different. 

GitHub md5 | GitHub size | pip (PyPi) md5 | pip (PyPi) size | FILE
-- | -- | -- | -- | --
45338cc8b975bdbbbead38d94e31e3df | 22 | 3f13b6997c472b30f152a726ff83b794 | 22 | *__init__.py
c738e8ce4177fe7e8be803586f2e11cb | 5 749 | 33fb9ab55230613b7bd303cf67d0f341 | 5 065 | *helpers\identity.py
05649099c79d3c1e52bceecb7ede7139 | 1 980 | c50d9b61b899157c028b9b771e6ebdf5 | 1 984 | *helpers\misc.py
d41d8cd98f00b204e9800998ecf8427e | 0 | d41d8cd98f00b204e9800998ecf8427e | 0 | *helpers\__init__.py
095c95d19d218dad6ca28ef24002ca38 | 4 260 | 24fcf8353718bca38526bd7d7973bf0c | 3 555 | *lib\base.py
67de3ea6b247026d3f6746e579c1aefa | 6 298 | 46d09eefd4d6b894b7b5a063955b75d6 | 5 965 | *lib\pybindJSON.py
ce4b13671eede4c669e76afe88824061 | 35 984 | d0885580de52ae86a1b02f38c9e8c897 | 21 008 | *lib\serialise.py
f150666b6f19e1ba101203d4ef47b54b | 13 400 | fc52122edf912a4df7b50837e117fb7e | 12 596 | *lib\xpathhelper.py
94bd772e7516f2fb7f63c41bafca3850 | 51 309 | 7b9b57f627274313e7693056b56f8a14 | 44 823 | *lib\yangtypes.py
d41d8cd98f00b204e9800998ecf8427e | 0 | d41d8cd98f00b204e9800998ecf8427e | 0 | *lib\__init__.py
432500e20d9931fee9dd4aed3de0a41c | 74 162 | 75e2bb28413d14c58227688ad935d276 | 67 663 | *plugin\pybind.py
d41d8cd98f00b204e9800998ecf8427e | 0 | d41d8cd98f00b204e9800998ecf8427e | 0 | *plugin\__init__.py

What is it?

**Comment by JoseIgnacioTamayo** [comment]
Hi,

I do not think this is a concern, the diffs are a few bytes and might have to do with python packaging.

As this represents no issue, closing it.
