### ISSUE TITLE
Appending to list doesn't retain nested lists

### ISSUE THREAD

**Issue by knollpoi** [robshakir/pyangbind#253]
The example below illustrates the behavior...

Example Module:

module example {
    yang-version 1.1;
    namespace "urn:com:example:exmod";
    prefix "exmod";
    container contA {
        list listA {
            key keyA;
            leaf keyA {
                type string;
            }
            leaf leafA1 {
                type string;
            }
            container contA1 {
                list A1 {
                    key keyA1;
                    leaf keyA1 {
                        type uint8;
                    }
                    leaf A1_leaf1 {
                        type string;
                    }
                }
            }
        }
    }
}

Example JSON input:
{
    "keyA": "instA",
    "leafA1": "instA_leafA1",
    "contA1": {
        "A1": {
            "0": {
                "keyA1": 0,
                "A1_leaf1": "A1_leaf1"
            },
            "1": {
                "keyA1": 1,
                "A1_leaf1": "A1_leaf1_2"
            }
        }
    }
}

TEST CODE 1: (Works as expected)
import pyangbind.lib.pybindJSON as pbJ
import pyangbind.lib.serialise as pbS
import json
from example import example
exb = example()
instA = exb.contA.listA.add('instA')
with open('example.json','r') as f:
   json_data = json.load(f)
pbS.pybindJSONDecoder.load_json(json_data, None, None, obj=instA)

print(instA.contA1.A1['0'].A1_leaf1)
PRINTS: A1_leaf1

print(exb.contA.listA['instA'].contA1.A1['0'].A1_leaf1)
PRINTS: A1_leaf1

Note that the nested list is addressable from the top-level list object.

TEST CODE 2: (nested list disappears)
import pyangbind.lib.pybindJSON as pbJ
import pyangbind.lib.serialise as pbS
import json
from example import example
exb = example()
instA = exb.contA.listA._new_item()
with open('example.json','r') as f:
   json_data = json.load(f)
pbS.pybindJSONDecoder.load_json(json_data, None, None, obj=instA)
exb.contA.listA.append(instA)

print(instA.contA1.A1['0'].A1_leaf1)
PRINTS: A1_leaf1

print(exb.contA.listA['instA'].contA1.A1['0'].A1_leaf1)

PRINTS: KeyError: '0'

Note that the nested list is not part of the top-level list even though it was part of the original instance that was created from the JSON and then appended to the top-level list object.

Is this expected?
How can I achieve the expected behavior using _new_item?

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing issue without recent updates.
