### ISSUE TITLE
Deserialize multiple elements in list

### ISSUE THREAD

**Issue by vaibhgupta157** [robshakir/pyangbind#257]
I have following json :

> test_json = {
>                         "cumulus-interfaces:interfaces": {
>                             "interface": [
>                                 {
>                                     "name": "swp1",
>                                     "bridge": {
>                                         "access": 102,
>                                         "allow-untagged": False
>                                     },
>                                     "name": "swp2",
>                                     "bridge": {
>                                         "access": 102,
>                                         "allow-untagged": False
>                                     }
>                                 }
>                             ]
>                         }
>                     }

where interface is a list in yang with key as name. I am trying to deserialize this json with following:

> new_config = pybindJSON.loads_ietf(test_json, cumulus_interfaces, "cumulus_interfaces")

When I tried to verify the object, I got only the second element in the list. 

>  print new_config.interfaces.get(filter=True)
> {'interface': OrderedDict([('swp2', {'bridge': {'access': 102L, 'allow-untagged': False}, 'name': u'swp2'})])}
>

**Comment by dimbleby** [comment]
There is only one element in that list, as you would see if you formatted it properly.

```
{
  "cumulus-interfaces:interfaces": {
    "interface": [
      {
        "name": "swp1",
        "bridge": {
          "access": 102,
          "allow-untagged": False
        },
        "name": "swp2",
        "bridge": {
          "access": 102,
          "allow-untagged": False
        }
      }
    ]
  }
}
```

**Comment by vaibhgupta157** [comment]
Thank You @dimbleby. This was an issue with formatting
