### ISSUE TITLE
"no format specified" when building a python module

### ISSUE THREAD

**Issue by horseinthesky** [robshakir/pyangbind#259]
Hello.
I've just started looking on YANG and I am trying to build a python module using pyang and pyangbind.

I've exported
```
export PYBINDPLUGIN=`/usr/bin/env python3 -c \
'import pyangbind; import os; print ("{}/plugin".format(os.path.dirname(pyangbind.__file__)))'`
```

but creation fails
```
pyang --plugindir $PYBINDPLUGIN -f pybind -o ietf_ip_binding.py ietf-ip.yang ietf-interfaces.yang ietf-inet-types.yang ietf-inet-types.yang
no format specified
```

**Comment by zhanggongc** [comment]
your problem is resolved   ? 
I also have this fail ,what is wrong  ?

**Comment by horseinthesky** [comment]
I haven't worked on this since then and have no time on it now.

**Comment by eissefo** [comment]
Try this:
pyang --plugindir=$PYBINDPLUGIN -f pybind -o ietf_ip_binding.py ietf-ip.yang ietf-interfaces.yang ietf-inet-types.yang ietf-inet-types.yang

**Comment by micafego** [comment]
I believe the python executable path was wrong. Try with `/usr/bin/env/python3`:
```
export PYBINDPLUGIN=`/usr/bin/env/python3 -c \
'import pyangbind; import os; print ("{}/plugin".format(os.path.dirname(pyangbind.__file__)))'`
```
