### ISSUE TITLE
ImportError: cannot import name 'pybindIETFXMLEncoder'!!

### ISSUE THREAD

**Issue by sindhujit** [robshakir/pyangbind#262]
Getting the subject line error. I used the latest pyangbind 0.8.1

**Comment by unsignedint** [comment]
You need the latest version i.e. master. The 0.8.1 does not include this feature.

**Comment by idefixcert** [comment]
Is a new release planned?
Or how to use the dependency for example in setup.py?

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing issue without recent updates.
