### ISSUE TITLE
pyang report a error ,what is wrong ? anyone know this problem  ?

### ISSUE THREAD

**Issue by zhanggongc** [robshakir/pyangbind#264]
root@debian:/home/cailei# pyang --plugindir $PYBINDPLUGIN -f pybind -o openconfig_acl.py ./openconfig/public/release/models/acl/openconfig-acl.yang -p ./openconfig/public/release/
no format specified
root@debian:/home/cailei# 

root@debian:/home/cailei/openconfig/public/release/models/acl# pyang --plugindir $PYBINDPLUGIN --format=pybind -o openconfig_acl.py openconfig-acl.yang
no format specified
root@debian:/home/cailei/openconfig/public/release/models/acl#

![image](https://user-images.githubusercontent.com/58503468/74718091-85071180-526c-11ea-8408-bf6dd331eb47.png)

![image](https://user-images.githubusercontent.com/58503468/74718130-93edc400-526c-11ea-8f16-75ea1335c551.png)

**Comment by aashaikh** [comment]
check the output of `echo $PYBINDPLUGIN` -- it is probably empty or incorrect;  this is the error if the plugin cannot be found that defines the pybind output format.   The pyangbind docs page describes how to set this variable.

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Could you please try again with recent versions of pyangbind?

Did the reply by @aashaikh  help?

Thanks.

**Comment by JoseIgnacioTamayo** [comment]
Closing issue without recent updates.
