### ISSUE TITLE
pybindIETEXMLEncode serialize class unable to maintain  xml hierarchy  as input value when I was use python 2.7

### ISSUE THREAD

**Issue by Ankushvin** [robshakir/pyangbind#280]
i have used pybindIETEXMLEncode class for serialize configuration which is in JSON format. 

So serialize xml output hierarchy got disturb when I used with python2.7, But same thing worked when I used python3.7. 

Do we have any restriction to use minimum python version to support pyangbind?

Do we have any way to restrict xml tag hierarchy when we generate from pybindIETFXMLEncoder.serialise() function? 

I have attached following file for checking purpose. 

1. autoconf.json---> This is json which has configuration which I want to render it. 
2. autoconf.yang---> This is yang schema file. 
3. program.py ---> This is a program which i wrote for generating  configuration in xml format using pyangbind. 
4. output ---> I have added actual and expected output in this file.

-------------------------
[autoconf.yang.t
[autoconf.json.txt](https://github.com/robshakir/pyangbind/files/7230699/autoconf.json.txt)
xt](https://github.com/robshakir/pyangbind/files/7230698/autoconf.yang.txt)
[program.py.txt](https://github.com/robshakir/pyangbind/files/7230703/program.py.txt)

[output.txt](https://github.com/robshakir/pyangbind/files/7230707/output.txt)
>

**Comment by JoseIgnacioTamayo** [comment]
Hi,

pyangbind is currently automatically tested with Python  >=3.7. 

I would suggest you move from python2 to python3.

I am closing this issue as python2 is deprecated.

https://www.python.org/doc/sunset-python-2/
