### ISSUE TITLE
Pyangbind PYPI release does not have pybindIETFXMLEncoder class

### ISSUE THREAD

**Issue by prabhuramani** [robshakir/pyangbind#287]
Hi,

Looks like this feature was added after the last release. It is in master but not released.
Are you planning to make a new release soon?

Thanks

**Comment by vjktm** [comment]
I had the same problem.
I seem to have fixed it in my local installation by:
1) downloading files from here to local machine
2) copy files from local to the local installation done by: 
`pip install pyangbind`
3) recreate the py bindings for your yang model
4) recreate the yang data in pythong with the new bindings
5) serialize to XML using steps shown in readme
