### ISSUE TITLE
How to inspect yang model

### ISSUE THREAD

**Issue by Saurabh29** [robshakir/pyangbind#288]
Hi,

I would like to use only to inspect yang model, basically would like to know
1. Type of leafs
2. All case in choice
3. Inspect List
I tried creating an instance and was able to get details type for leaf etc, however in case of list I am unable to proceed.

Regards
Saurabh

**Comment by JoseIgnacioTamayo** [comment]
Hi Saurabh29,

Reproducing your issue is key to understand it and fix it.

 * How are you using pyangbind? An extract of your code would be helpful.
 * What would you expect to obtain when inspecting a list? An example would be helpful.

Looking forward to helping you with the issue.

**Comment by JoseIgnacioTamayo** [comment]
Closing, as there was no follow up on the issue.
