### ISSUE TITLE
pyangbind fails to install via PyPi

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#29]
OS: Windows 10
IDE: PyCharm Community Edition 5.0.2
Repo: https://pypi.python.org/pypi
Python: 2.7.11 (venv)
PyangBind version: 0.2.1

Attempt to install pyangbind into my venv gives me the following error (extraneous detail omitted)

>    ERROR: 'xslt-config' is not recognized as an internal or external command,
>    operable program or batch file.
>    
>    ** make sure the development packages of libxml2 and libxslt are installed **

..

>file: 'libxml/xpath.h': No such file or directory
>    *********************************************************************************
>    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?

Is there a package dependency I'm missing? I tried installing libxml2-python, however that installation fails too:

>Collecting libxml2-python
>
>  Could not find a version that satisfies the requirement libxml2-python (from versions: )
>No matching distribution found for libxml2-python

**Comment by robshakir** [comment]
Unfortunately I have zero way to debug this on Windows - and it doesn't sound like it's a PyangBind issue (more a lxml one -- `xslt-config` is called by lxml I believe). Did you look at instructions as per something like http://www.laurivan.com/install-lxml-on-windows-on-a-virtualenv/ ?

It may also be useful to try and install this from a binary (egg, or wheel) such that you don't end up trying to make the whole build (which pip seems to do by default).

Cheers,
r.

**Comment by mpainenz** [comment]
Thanks Rob, I will try to get this working via the PyPi route, but for now I've reverted back to my previous installation method.

For anyone else who encounters this... a temporary workaround is to include the \lib directory in your own project. Some minor changes to serialise.py may be required (remove "pybind" from the classes in the default() function.

**Comment by mpainenz** [comment]
Hi Rob,

I found that yes, this was an lxml dependency issue, and that installing lxml from pypi fixed the problem.

I realise that this isn't a pyangbind issue, but I thought I would mention that the instructions on the page you linked, and manually installing in the way described can be circumvented. lxml installed for me via pypi (3.5.0 didn't work, but 3.4.4 worked)

**Comment by mpainenz** [comment]
I should mention as well that I have moved to using pyangbind from the pypi version rather than including the github source in my \lib dir. No problems so far
