### ISSUE TITLE
Is pyangbind still maintained?

### ISSUE THREAD

**Issue by XioNoX** [robshakir/pyangbind#292]
Hi,

It seems like this project haven't seen any update since 2018, so I'm assuming it's not maintained anymore.

Is https://github.com/CiscoDevNet/ydk-gen/ the only alternative to generate python bindings from yang models? Is there an industry standard/agreement in that domain?

Thanks!

**Comment by gusmb** [comment]
I am also interested on this topic. This package seems to be one of the most convenient methods to  work with YANG models natively in Python. I'm missing some key things like correct handling of YANG defaults (I am not able to serialize them), handling of some YANG constraints (when, must) don't work (binding object loads correctlly when it should error out), or implementing lazy validation to get a list of YANG instance data errors. I have a workaround for this validation using Yangson with JSON serialized data, but it would be ideal if pyangbind could be the goto place for all this and could be further maintained.

**Comment by xavier-contreras** [comment]
Thanks for the interest!  A couple of us just got onboarded as maintainers and we'll be tidying things up.   Looking forward to keeping this project going.

**Comment by JoseIgnacioTamayo** [comment]
Yes, indeed the intention is to maintain this project.

@gusmb , could you please raise all the features as GitHub Issues? Then anyone can implement them and propose PullRequests.

I will close this Issue as it has answered the question: yes, there is commitment to maintain pyangbind.
