### ISSUE TITLE
unsupported format 'pybind'

### ISSUE THREAD

**Issue by ashishk1994** [robshakir/pyangbind#30]
I am trying to bind using following command but getting unsupported format 'pybind' error.

sudo pyang --plugindir site-packages/pyangbind/plugin -f pybind turing-machine.yang -o bindings.py

Can someone please help me with this.

**Comment by robshakir** [comment]
Hi,

Can you provide the output of:

```
/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'
```

You should use whatever path is supply there (ideally the absolute path, rather than the relative one) after --plugindir. 

This error (unsupported format) means that pyang is not finding the plugindir with `pybind.py` in it.

Cheers,
r.

**Comment by ashishk1994** [comment]
Hi,
For below command,
```
/usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'
```
output is : /usr/local/lib/python2.7/dist-packages/pyangbind-0.2.1-py2.7.egg/pyangbind/plugin


I tried with above path as follows:

```
pyang --plugindir /usr/local/lib/python2.7/dist-packages/pyangbind-0.2.1-py2.7.egg/pyangbind/plugin -f pybind turing-machine.yang -o bindings.py
```

It is still giving me the same error.
```
unsupported format 'pybind' error.
```

**Comment by robshakir** [comment]
Does your user have permission to read the `/usr/local/lib/python2.7/dist-packages/pyangbind-0.2.1-py2.7.egg/pyangbind/plugin/pybind.py` file? What version of pyang are you running, and on what distro (I assume Linux)?

**Comment by ashishk1994** [comment]
I tried it with the sudo but still the same error.
I am using pyang 1.6. pyang --version 
```
pyang 1.6
```
and ubuntu 12.04
My plugin directory is :
 ```/usr/local/lib/python2.7/dist-packages/pyangbind-0.2.1-py2.7.egg/pyangbind/plugin```
Why did you put pybind.py at the last?

**Comment by robshakir** [comment]
`pybind.py` is the file that defines the format of `pybind` that your pyang is reporting it can't find.

How did you install pyangbind? I note that you have an egg specified in that path, but I only upload a wheel and sdist to PyPI. When I install it through pip on any Linux I have access to, it's never within an egg.

**Comment by ashishk1994** [comment]
Actually I was using pip version 1.2 . I upgraded the pip on my system then installed pyangbind again. It worked.
Thanks

**Comment by robshakir** [comment]
Great - closing.
