### ISSUE TITLE
Failure on OpenConfig BFD Model

### ISSUE THREAD

**Issue by wenovus** [robshakir/pyangbind#302]
There is a failure when I generate against the latest OpenConfig BFD model:
https://gist.github.com/OpenConfigBot/f2158a52bc907ed4e690582d47f2af61

```
File "/workspace/bfd.openconfig-bfd.binding.py", line 2320
    async = __builtin__.property(_get_async)
          ^
SyntaxError: invalid syntax
```

You can reproduce with the following command:

OC_WORKSPACE=</path/to/oc/public/repo>
```bash
pyang --plugindir $PYANGBIND_PLUGINDIR -o bfd.openconfig-bfd.binding.py -f pybind -p $OC_WORKSPACE/release/models -p $OC_WORKSPACE/third_party/ietf $OC_WORKSPACE/release/models/bfd/openconfig-bfd.yang
```

Can you help take a look? grepping for `async` didn't give me anything in the repo.

**Comment by JoseIgnacioTamayo** [comment]
Hi Wen,

Yes, we know of this problem. See
https://github.com/robshakir/pyangbind/pull/285.

Soon we will be publishing this and other fixes for pyangbind. Have just a
little patience.

Feel free to comment on the GitHub issue to record the fact that the bug
affects you.

Thanks, and all the best.

Jose Ignacio Tamayo Segarra
LinkedIn <http://br.linkedin.com/in/joseignaciotamayosegarra>

**Comment by JoseIgnacioTamayo** [comment]
Fixed in https://github.com/robshakir/pyangbind/pull/285
