### ISSUE TITLE
Support `bits` type

### ISSUE THREAD

**Issue by tehAgitto** [robshakir/pyangbind#314]
Hello,

is it possible to support `bits` type? I've tried to convert YANG model into pydantic `BaseModel`, but it seems not every type is supported (I've read docs). Do you have it on your roadmap anywhere?

```python
could not find a match for SOME type -> ['bits']
```

**Comment by fperrin** [comment]
Hi @tehAgitto ,

For `$work` I added support for the bits type. The code is there: https://github.com/fperrin/pyangbind/commits/fred/add-bits

It's working well enough for the models I use, but I never got around to creating a PR to get it included. I think I need to review it.
