### ISSUE TITLE
__yang_order in the YANG lists

### ISSUE THREAD

**Issue by ashishk1994** [robshakir/pyangbind#32]
Hi,

I am adding some values to the YANG list. In the output I am getting an extra field of  "__yang_order". Can someone please tell me how to remove it from the output because I think it is for some internal use of pyangbind which is getting reflected to my final output.

```
{'locator_id': 'ISP1'}
{'hop_id': 'Hop 1'}
{'hop_id': 'Hop 2'}
{
    "input": {
        "LocatorRecord": {
            "ISP1": {
                "locator-id": "ISP1", 
                "rlocProbed": false, 
                "weight": 1, 
                "multicastPriority": 255, 
                "localLocator": true, 
                "routed": false, 
                "priority": 1, 
                "rloc": {
                    "address-type": "ietf-lisp-address-types:explicit-locator-path-lcaf", 
                    "explicit-locator-path": {
                        "hop": {
                            "Hop 1": {
                                "__yang_order": 0, 
                                "hop-id": "Hop 1", 
                                "lrs-bits": "lookup rloc-prob strict", 
                                "address": "20.20.20.20"
                            }, 
                            "Hop 2": {
                                "__yang_order": 1, 
                                "hop-id": "Hop 2", 
                                "lrs-bits": "lookup strict", 
                                "address": "30.30.30.30"
                            }
                        }
                    }
                }, 
                "multicastWeight": 0
            }
        }, 
        "mapping-record": {
            "recordTtl": 1440, 
            "action": "NoAction", 
            "authoritative": true, 
            "mapVersion": 10
        }
    }
}
```

**Comment by robshakir** [comment]
Hi,

Sorry -- I missed this. This is a meta-data element that is added when OrderedDict is used with the existing JSON encoding here. The reason for this is that there may be re-ordering of the entries in the JSON object - since it has no strict ordering.

At the moment, there is not a flag to turn this off -- one could be added. Additionally, I am looking at implementing a serialisation format compliant with the IETF JSON encoding for YANG.

Cheers,
r.

**Comment by ashishk1994** [comment]
Hi Rob,

Can you please guide me how to shut it off temporarily till the IETF JSON encoding.

**Comment by robshakir** [comment]
Ashish,

The IETF JSON encoding has been released for some time - please see the documentation at http://pynms.io/pyangbind/serialisation/#serialising-json or the example code in the https://github.com/robshakir/pyangbind/tree/master/docs/example/simple-serialise directory.

Kind regards,
r.

**Comment by robshakir** [comment]
I'll close this issue based on the availability of the IETF JSON encoding.
