### ISSUE TITLE
pyangbind-0.8.4 installation failed

### ISSUE THREAD

**Issue by asn-lns-sa-rj** [robshakir/pyangbind#324]
Cannot install new version 0.8.4.

$ pip install pyangbind --upgrade
...
    Found existing installation: pyangbind 0.8.3.post1
    Uninstalling pyangbind-0.8.3.post1:
      Successfully uninstalled pyangbind-0.8.3.post1
Successfully installed pyangbind-0.8.4

Contrary to expectation, the folder contains only the __init__.py file, not the subfolders (helpers, lib, plugin)

Then rollback: 
$ pip uninstall pyangbind
$ pip install --upgrade pyangbind==0.8.3.post1
... Successfull

**Comment by JoseIgnacioTamayo** [comment]
Oh my... Something went wrong with the package done and uploaded with GitLab Actions.

I just built and uploaded 0.8.4.post1. It looks OK to me, please give it a try.

Apologies for the inconvenience.

**Comment by asn-lns-sa-rj** [comment]
Thank you for your quick support, Jose.
I confirm it works fine now.
Regards
