### ISSUE TITLE
Can not be directly used in ncclient?

### ISSUE THREAD

**Issue by Dulin0411** [robshakir/pyangbind#326]
Hi,

I found the xml created by pyangbind can not uesd in ncclient directly.
The xml pyangbing created is as follow
`<ietf-interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interfaces>
    <interface>
      <name>Twe1/0/1</name>
      <enabled>false</enabled>
    </interface>
  </interfaces>
</ietf-interfaces>`

The xml ncclient can edit-config directly is as follow
`<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface>
          <name>Twe1/0/1</name>
          <enabled>false</enabled>
        </interface>
      </interfaces>
</config>`

The code I used is as follow, if I used in wrong way?

from pyangbind.lib.serialise import pybindIETFXMLEncoder
from ietf_interfaces import ietf_interfaces
configs = ietf_interfaces()
ret = configs.interfaces.interface.add('Twe1/0/1')
ret.enabled = 'false'
config = str(pybindIETFXMLEncoder.serialise(configs))
print(config)

**Comment by JoseIgnacioTamayo** [comment]
Hi,

Have you tried with `config = str(pybindIETFXMLEncoder.serialise(configs.interfaces))`

My idea is to tell pyangbind to generate the output starting at the <interfaces> element.

**Comment by Dulin0411** [comment]
Thanks for your suggestion，It‘s worked.
