### ISSUE TITLE
IETF JSON serialisation issue for non-empty presence container

### ISSUE THREAD

**Issue by dfischer-de** [robshakir/pyangbind#350]
I've noticed that there have been a lot of improvements to support presence containers lately ([issue 336](https://github.com/robshakir/pyangbind/issues/336)). Many thanks to the community!
I ran into another problematic case: if a presence container has another empty container or leaf and the presence is set, IETF JSON serialisation does not work for this container.

I was able to reproduce it with test yang model for presence testing (https://github.com/robshakir/pyangbind/blob/master/tests/presence/presence.yang)
I create binding using --presence flag:

```
pyang --plugindir $PYBINDPLUGIN --presence -f pybind -o /opt/gnmi/tests/presence.py presence.yang
```
I set presence for p-container and try JSON serialisation in IETF and default mode:
```
>>> from presence import presence
>>> p = presence()
>>> p.p_container._set_present(True)
>>> import pyangbind.lib.pybindJSON as pybindJSON
>>> pybindJSON.dumps(p, indent=None)
'{"p-container": {}}'
>>> pybindJSON.dumps(p, mode="ietf", indent=None)
'{}'
```
As you can see, the container is not shown in IETF serialisation mode.

Related versions:
> pyang 2.6.1
pyangbind 0.8.5

Any help would be greatly appreciated!

**Comment by JoseIgnacioTamayo** [comment]
I guess I reproduced the issue, and show it in the Unit Tests for Presence.

https://github.com/robshakir/pyangbind/compare/master...fix/presence_serialization_emptycontainer

Once I get the fix, I will create a PR.

**Comment by JoseIgnacioTamayo** [comment]
@dfischer-de , could you please try if [fix/presence_serialization_emptycontainer](https://github.com/robshakir/pyangbind/tree/fix/presence_serialization_emptycontainer) works for you?

**Comment by dfischer-de** [comment]
> [JoseIgnacioTamayo](/JoseIgnacioTamayo)

Yes, this fix solved my issue.
Thank you!
