### ISSUE TITLE
Import In Yang Models

### ISSUE THREAD

**Issue by ashishk1994** [robshakir/pyangbind#38]
Hi,

I was trying to parse the yang models using pyangbind. It includes import, does pyangbind plugin supports import because, I am getting following error.

```
pyangbind-example.yang:36: error: unexpected keyword "import"
pyangbind-example.yang:36: error: module "ietf-yang-types" not found in search path
pyangbind-example.yang:36: warning: imported module ietf-yang-types not used
FATAL: pyangbind cannot build module that pyang has found errors with.
```

My file is something like:
```
module pyangbind-example {
        namespace "urn:ietf:params:xml:ns:yang:ietf-lisp-address-types";
        prefix laddr;
        import ietf-yang-types { prefix yang; }

       // Omitted later part
```
Please help me if I am missing something. I am new to yang models and trying to understand various yang concepts as well.

**Comment by robshakir** [comment]
Yes, pyangbind supports import. The errors that you see there are from the pyang standard validation phases, pyangbind will not attempt to build bindings for a YANG module that pyang has already found errors for (excepting some minor warnings). You should ensure that running `pyang <module-path>` does not produce any errors prior to trying to generate bindings.

There are a number of examples of YANG modules in the `test` directory of this repo that you can base your modules on.

Thanks,
r.
