### ISSUE TITLE
Create a more flexible error type for Pyangbind

### ISSUE THREAD

**Issue by robshakir** [robshakir/pyangbind#47]
The errors returned today are too verbose, and do not give useful information - update them to be more user-friendly.

**Comment by robshakir** [comment]
As per the above commits, a new payload to standard Python errors has been added -- please see [the new docs](https://github.com/robshakir/pyangbind/blob/master/docs/errors.md), I'd really appreciate the feedback.

r.

**Comment by JoseIgnacioTamayo** [comment]
Closing issues without recent activity.
