### ISSUE TITLE
Is there a way to append an existing Object to a Keyed List?

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#49]
Hi Rob,

In the case of a Keyed list, is it possible to append an item which has already been instantiated to the list?

Currently my code looks like this when creating list items:

```
ep_list = ep_container.endpoint
ep = ep_list.add(registration_id="Test-Endpoint")
```

What I would like to achieve is the following:

```
ep_list = ep_container.endpoint
ep = yc_endpoint_endpoints__endpoints_endpoint()
ep.registration_id = "Test-Endpoint"
ep_list.add(ep)
```

Alternatively some sort of Assign might be useful:

```
ep1 = yc_endpoint_endpoints__endpoints_endpoint()
ep2 = yc_endpoint_endpoints__endpoints_endpoint()
ep1.assign(ep2)

```

**Comment by robshakir** [comment]
Hi Mark,

This did used to be possible, but unfortunately it got broken when I added some checks about overwriting objects in the list, and the `kwarg` add functions.

In https://github.com/robshakir/pyangbind/commit/0c28c057eeb7034c23c94a4e7ec09a9fd2ae00d0 (rather a hefty commit, since it's on my working branch) then these functions are restored as I'd noted this as part of a wider set of usability fixes that I'm adding based on an internal implementation.

Essentially, if we have a module:

```
module pond {
    namespace "http://rob.sh/pond";
    prefix "pond"; 

    list fish {
        key "type";

        leaf type {
            type string;
        }
        
        leaf number-in-pond {
            type uint64;
        }
    }
}
```

Then with bindings generated from the `docs` branch, then the following is now possible:

```python
#!/usr/bin/env python

from ybind import pond
from ybind.fish import fish

p = pond()

f = fish()
f.type = "salmon"
f.number_in_pond = 42

p.fish.add(type=f.type, _v=f)

print p.get(filter=True)

p.fish.add(type="koi")
passed = False
try:
    p.fish["koi"].type = "walrus"
except AttributeError:
    passed = True

assert passed is True, "Should not be able to modify a list item key value"

p.fish._item(type="koi").number_in_pond = 99

print p.get(filter=True)
```

This will output:

```
[~/Code/pyangbind/tmp(docs*)]
(17:19 - s001) latte> python pondtest.py
{'fish': {u'salmon': {'type': u'salmon', 'number-in-pond': 42}}}
{'fish': {'koi': {'type': u'koi', 'number-in-pond': 99}, u'salmon': {'type': u'salmon', 'number-in-pond': 42}}}
```

HTH,
r.

**Comment by mpainenz** [comment]
Rob, this is great, I especially like this notation: `p.fish[f.type] = f`

Thanks for the commit, that was awesomely fast!

**Comment by mpainenz** [comment]
Look forward to this getting pushed, I still have not worked out how to pull a specific commit with my GIT client

**Comment by robshakir** [comment]
It's now merged to `master` - please feel free to play.

BTW, to get commits on the branch referenced above, you need the equivalent of `git checkout docs` where `docs` is the branch name.

**Comment by mpainenz** [comment]
Hi Rob,

Not sure if I'm doing something wrong, but I can't pull the `docs` branch.

```git.exe pull -v --progress  "origin" docs

fatal: Couldn't find remote ref docs


git did not exit cleanly (exit code 1) (1281 ms @ 24/03/2016 10:29:32 AM)
```

I can oddly enough 'see' the branch name via the GUI of my GIT client, is it a private branch?

The BIT Webpage doesn't display the `docs` branch @ https://github.com/robshakir/pyangbind/branches

**Comment by mpainenz** [comment]
Sorry, I missed the part about the branches being merged

**Comment by mpainenz** [comment]
OK, so I've been playing around, using the example from issue #35 

Simplified YANG of the list

```
list ping-invite-response-code-range {
  key "low";
  leaf low {
    type uint16 {
      range "400..699";
    }
  }
  leaf high {
    description
    type uint16 {
      range "400..699";
    }
  }
}
```

The following example:

```
test = ep.sip.monitoring.ping_invite_response_code_range._contained_class()
test.low = 403
test.high = 403
ep.sip.monitoring.ping_invite_response_code_range[test.low] = test
```

Gives the following error:

```
  File "C:\Projects\git\genband-oneems-service\src\worker\endpointworker.py", line 91, in run_test
    ep.sip.monitoring.ping_invite_response_code_range[test.low] = test
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 1014, in __setitem__
    super(YANGBaseClass, self).__setitem__(*args, **kwargs)
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 559, in __setitem__
    self.__set(_k=k, _v=v)
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 641, in __set
    load=True)
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 1065, in YANGDynClass
    return YANGBaseClass(*args, **kwargs)
  File "C:\Projects\git\genband-oneems-service\pyangbind\lib\yangtypes.py", line 961, in __init__
    % (type(e), e))
TypeError: couldn't generate dynamic type -> <type 'exceptions.AttributeError'> -> Cannot set keys directly when within an instantiated list
```

**Comment by robshakir** [comment]
I don't think you're running master (I didn't publish this on PyPI yet):

```python
>>> from alistbind import alist
>>> a = alist()
>>> 
>>> t = a.ping_invite_response_code_range._contained_class()
>>> 
>>> t.low = 400
>>> t.high = 412
>>> 
>>> a.ping_invite_response_code_range[t.low] = t
>>> a.ping_invite_response_code_range.get()
{400: {'high': 412, 'low': 400}}
```

You also need to regenerate the bindings - since the error you're seeing is calling `super().__init__` for the class, which actually calls the bindings again. This needed a kwarg added in the bindings (which I try and avoid - but it was needed here).

[The reason for the kwarg addition is that we need to make sure that someone doesn't manipulate the key of an existing object in general - i.e., say that `list["foo"].keyleaf = "bar"`, because this would end up with strange inconsistencies in the dataset.]

**Comment by mpainenz** [comment]
Oh right, I'm definately on Master, but I did not regen the bindings. Will give that a go, thanks

**Comment by robshakir** [comment]
No worries, thanks.

As of the latest commit, one can now tell the module version this way too:

```python
>>> import pyangbind
>>> pyangbind.__version__
'0.4.1'
```

**Comment by mpainenz** [comment]
Thanks Rob, that has worked. 

I'm going to leave this open, as I did have more questions on this. Namely around some code I'm trying to right with dynamically creates and appends list items, where the list keys could be anything. 

I'm not sure how to achieve this, but I'll have a play around and come back with something specific if I can't manage to get it working.

Thanks,
Mark

**Comment by mpainenz** [comment]
OK, so the code I had written to do dynamic loading/appending of list items worked.

I was a little suprised, as I expected to get some type issues. 

All of the following works:

```
ep.sip.monitoring.ping_invite_response_code_range[test.low] = test
ep.sip.monitoring.ping_invite_response_code_range[403] = test
ep.sip.monitoring.ping_invite_response_code_range["403"] = test
```

I would have to assume that the following would work:

`some_list_with_two_key_fields["key_field_1 key_field_2"] = test`

In which case, I'm very happy, as my existing placeholder code will work for all cases :dancer:

**Comment by robshakir** [comment]
`ep.sip.monitoring.ping_invite_response_code_range["403"] = test` is valid because `int("403") == 403` - PyangBind tries to embrace Duck-Typing - so what it does is try and cast whatever you give it into the right type - it's only when there is no way that we can make the value fit the specification that an error is thrown.

If one were to use a strictly-typed language, then this wouldn't work of course, but it feels more Pythonic to me.

**Comment by mpainenz** [comment]
That's great, it works very well. 

The only possible improvement would be a list append method which doesn't require you to specify the key value. In case someone else runs into this in the mean time, here is my code modified from your example elsewhere

```
def _build_key_string(self, list_obj, item_obj):
    kp = list_obj._keyval.split(" ")
    if len(kp) > 1:
        ks = unicode()
        for k in kp:
            kv = getattr(item_obj, "_get_%s" % yangtypes.safe_name(k))
            ks += unicode(kv()) + " "
        return ks.rstrip(" ")
    else:
        return getattr(item_obj, "_get_%s" % yangtypes.safe_name(kp[0]))()

item_list = list_class()
item = item_list ._contained_class()
item.key_field_1 = "some alpha value"
item.key_field_2 = 123456

key_string = self._build_key_string(item_list, item)
some_list [key_string] = item
```

Would really like to simplify that to:

```
item_list = list_class()
item = item_list ._contained_class()
item.key_field_1 = "some alpha value"
item.key_field_2 = 123456
some_list.append(item)
```

**Comment by robshakir** [comment]
Voila:

f0f42a82eaa0f76ea84aa066143f84e4e8b9f5ec - Documentation
9fd299c0a138a10ffd2ba8b8374e183c879c5a7a - Code

Enjoy,
r.

**Comment by mpainenz** [comment]
Thanks Rob, great work. My code is getting simpler by the hour!

Cheers,
Mark
