### ISSUE TITLE
Restriction/Range that uses keyword 'min' does not work

### ISSUE THREAD

**Issue by mpainenz** [robshakir/pyangbind#62]
Hi Rob,

Please see pull request #61

I've included an example in my pull request (texts\int\int.yang) to demonstrate the broken functionality, but here's an example:

```
leaf restricted-ueight-min-alias {
    type int8 {
        range "min..max";
    }
}
```

I couldn't work out where the min and max keywords get translated into an integer representation. Perhaps it's done via pyang, I don't know.

Thanks,
Mark

**Comment by robshakir** [comment]
See comments in #61. This will be fixed when #63 is merged.

Please take a look 🔬 

Cheers,
r.
