### ISSUE TITLE
Extensions are not put in the dictionary for containers

### ISSUE THREAD

**Issue by arthurlena** [robshakir/pyangbind#69]
Hi,
I had a problem where extensions for a model are not added to the extensions dictionary when they are specified for a container. 
I used the following setup:

- the file [test.yang.txt](https://github.com/robshakir/pyangbind/files/293090/test.yang.txt) contains a YANG test data model

- the file [test-ext.yang.txt](https://github.com/robshakir/pyangbind/files/293094/test-ext.yang.txt) contains an extension to the test data model.

The python classes have been generated using the following command:
`pyang --plugindir /path/to/python/venv/lib/python2.7/site-packages/pyangbind/plugin --interesting-extension test-ext -f pybind -o test.py test.yang`

The following results are observed (ipython output):
`In [1]: import test`
`In [2]: test.test()._get_c1()._extensions()`
`In [3]: test.test()._get_l1()._extensions()`
`Out[3]: {u'test-ext': {u'version': u'1.0'}}`

Aren't the extensions supposed to be extracted also for containers?

**Comment by robshakir** [comment]
Hi!

Thanks for reporting this bug. Please see the above commit - I'll package this up tomorrow and push it to PyPi as v0.5.4.

The tests in `tests/extensions` should show the resolution to this issue - insofar as testing that lists, list entries and containers all carry the relevant extensions.

Thanks again!
r.

**Comment by robshakir** [comment]
Apologies, also meant to say: please feel free to re-open this is you don't find it resolved as you expected!

r.

**Comment by arthurlena** [comment]
Hi!

I finally had time to check this using the git master branch. Seems to be working fine, thanks for fixing this so quickly.

Arthur

**Comment by robshakir** [comment]
No problems, thanks for the bug report - the example made things super-easy to validate.

r.
