### ISSUE TITLE
Empty container is not captured in the binding

### ISSUE THREAD

**Issue by sangwookha-vz** [robshakir/pyangbind#70]
When a container is specified without any child, the container is not captured in the classes generated by pyangbind (version 0.5.2). For example, new-topo.yang with the following content:

    module new-topo {
        namespace "urn:network:new-topo";
        prefix "new-topo";

        container network-types {
            container new-net {
                presence "Presence of this container indicates that network type is new-net";
            }
        }
    }

Pyangbind does not create a class for new-net.

Output of pyang --strict -f tree new-topo.yang:

    module: new-topo
       +--rw network-types
          +--rw new-net!

**Comment by robshakir** [comment]
Hi,

This was currently a design choice. Pyangbind would currently generate something that looks like:

```
class new_net(object):
      _pyangbind_elements = {}
```

This class seems relatively useless - since I'm not sure what one would do to manipulate it. Currently, there is no support for the `presence` keyword. Could you explain to me how you would expect to use this such that we can design how this would work?

Thanks,
r.

**Comment by sangwookha-vz** [comment]
In the [IETF network model](https://datatracker.ietf.org/doc/draft-ietf-i2rs-yang-network-topo/) they use presence to indicate the network types.

In section 3.4.8. it says:

    A network's network types are represented using a container which
    contains a data node for each of its network types.  A network can
    encompass several types of network simultaneously, hence a container
    is used instead of a case construct, with each network type in turn
    represented by a dedicated presence container itself.  The reason for
    not simply using an empty leaf, or even simpler, do away even with
    the network container and just use a leaf-list of network-type
    instead, is to be able to represent "class hierarchies" of network
    types, with one network type refining the other.  Network-type
    specific containers are to be defined in the network-specific
    modules, augmenting the network-types container.

In the model it has the following:

    container network-types {
      description
        "Serves as an augmentation target.
         The network type is indicated through corresponding
         presence containers augmented into this container.";
    }

I couldn't load JSON data which has a network type specified with an empty container.

**Comment by robshakir** [comment]
Right - but how would you want to interact with this in Python?

One option would be to have something in the meta-class that lets one set the presence, for example:

```python
model.container._presence = True
```

This would then set `_changed` to `True` as well, which would mean that it would be serialised when creating JSON instances.

When de-serialising we would need to understand that ```"model": { "container": {} }``` meant that `_presence` for `container` needed to be set, but that is something that we could do relatively easily in the `lib.serialise` modules.

Would this make sense for you?

r.

**Comment by sangwookha-vz** [comment]
Yes, that makes sense to me.

One question: if there is a hierarchy of presence containers, how can it be handled?

    container network-types {
        container type-a {
            presence "type-a";
            container type-a-1 {
                presence "type-a-1";
            }
        }
    }

When serializing should `_presence` for both `type-a` and `type-a-1` be set `True` to include `type-a-1` container?

**Comment by robshakir** [comment]
I would see that `_presence` would work like `_mchanged` where hierarchically it would be `True` if any descendent was set. I'll look into implementing this over the coming few days.

**Comment by robshakir** [comment]
Hi @sangwookha-vz,

If you pull the `presence` branch - the functionality that we discussed above is implemented therein.

You can see some examples of how to use it in https://github.com/robshakir/pyangbind/blob/presence/tests/presence/run.py

Any comments very welcome.

Cheers,
r.

**Comment by robshakir** [comment]
I merged this branch and released it to PyPI. If there are issues, please do let me know.

Cheers,
r.
