### ISSUE TITLE
Unable to resolve a submodule's imported type

### ISSUE THREAD

**Issue by cho-m** [robshakir/pyangbind#81]
In the case that a submodule uses the type of one of its imported modules, pybind is unable to resolve the type when run on the module which includes the submodule. The following is a simple example to reproduce this issue.

The error from running pybind is:
```
$ pyang --plugindir $PYBINDPLUGIN -f pybind -o a.py a.yang
FATAL: unmapped type (c:t)
[ 'int32',
  'int16',
  'string',
  'uint8',
  'boolean',
  'int8',
  'uint64',
  'binary',
  'decimal64',
  'uint16',
  'int64',
  'uint32',
  'empty']
u'c:t'
False
```

There is no issue when run with pyang's tree format:
```
$ pyang -f tree a.yang
module: a
   +--rw a
      +--rw b?   c:t
```

Definition of module fed to pyang command:
```yang
module a {
  namespace "http://example.com/a";
  prefix a;
  include b;

  container a {
    uses TEST;
  }
}
```

Definition of submodule:
```yang
submodule b {
  belongs-to a { prefix a; }
  import c { prefix "c"; }

  grouping TEST {
    leaf b {
      type c:t;
    }
  }
}
```

Definition of imported module with typedef:
```yang
module c {
  namespace "http://example.com/c";
  prefix "c";

  typedef t {
    type string;
  }
}
```

I have added `modules.append(subm)` on line 349 (mirroring behavior in 'import' loop) to deal with this, but I haven't checked if this causes any issues.

**Comment by robshakir** [comment]
Thanks for reporting this issue. I've added a check specifically for imports inside of submodules which resolves the case that you mentioned. Please pull the HEAD of `master` and check if you get a moment!

Thanks,
r.
