### ISSUE TITLE
Support for derived identity inside submodule

### ISSUE THREAD

**Issue by cho-m** [robshakir/pyangbind#82]
The current implementation of pybind's `build_identities`does not support defining derived identity inside submodules. An error occurs due to line 452 where pybind tries to look up a namespace which doesn't exist:
```python
 450       if unicode(base.arg) in identity_d:
 451         base_id = unicode(base.arg)
 452         namespace = defnd[ident].i_module.search_one('namespace').arg
 453         module = defnd[ident].i_module.arg
 454         defn_content = {'@namespace': namespace, '@module': module}
```

The result is: `AttributeError: 'NoneType' object has no attribute 'arg'`

A simple submodule to reproduce issue:
```yang
submodule b {
  belongs-to a { prefix a; }
  identity i { }
  identity j { base i; }
}
```

**Comment by robshakir** [comment]
Hi,

I've added a check to ensure that the namespace and module parameters are properly looked up against the parent module, and this is now resolved. Please check HEAD@`master` to verify!

Thanks,
r.
