### ISSUE TITLE
could not resolve typedefs error

### ISSUE THREAD

**Issue by freeze91** [robshakir/pyangbind#85]
Hi,

I faced an issue in compiling the attached yang file acl-example.txt (taken from OpenConfig public release for acl model with modification) using pyangbind with the following error:

[acl-example.txt](https://github.com/robshakir/pyangbind/files/410559/acl-example.txt)

$ pyang --plugindir $PYBINDPLUGIN -f pybind -p $SDIR/ -o $SDIR/binding.py $SDIR/acl-example.yang
could not find a match for acl:ethertype-type type -> [u'uint16', u'identityref']
could not find a match for acl:ip-protocol-type type -> [u'uint8', u'identityref']
could not find a match for ethertype-type type -> [u'uint16', u'identityref']
could not find a match for ip-protocol-type type -> [u'uint8', u'identityref']
Traceback (most recent call last):
  File "/usr/local/bin/pyang", line 4, in <module>
    __import__('pkg_resources').run_script('pyang==1.7', 'pyang')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1651, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/pyang-1.7-py2.7.egg/EGG-INFO/scripts/pyang", line 434, in <module>
    run()
  File "/usr/local/lib/python2.7/site-packages/pyang-1.7-py2.7.egg/EGG-INFO/scripts/pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "/usr/local/lib/python2.7/site-packages/pyangbind-0.5.7-py2.7.egg/pyangbind/plugin/pybind.py", line 211, in emit
    build_pybind(ctx, modules, fd)
  File "/usr/local/lib/python2.7/site-packages/pyangbind-0.5.7-py2.7.egg/pyangbind/plugin/pybind.py", line 389, in build_pybind
    build_typedefs(ctx, defn['typedef'])
  File "/usr/local/lib/python2.7/site-packages/pyangbind-0.5.7-py2.7.egg/pyangbind/plugin/pybind.py", line 590, in build_typedefs
    raise TypeError("could not resolve typedefs %s" % error_ids)
TypeError: could not resolve typedefs [u'acl:ethertype-type', u'acl:ip-protocol-type', u'ethertype-type', u'ip-protocol-type']

After simple debugging I found out that these lines were causing the problem, identityref inside a union type, and deleting the identityref works:

  typedef ip-protocol-type {
    type union {
      type uint8 {
        range 0..254;
      }
      type identityref {
        base IP_PROTOCOL;
      }
    }
    description
      "The IP protocol number may be expressed as a valid protocol
      number (integer) or using a protocol type defined by the
      IP_PROTOCOL identity";
  }

The use case for this would be in creating an ACL model with packet matching arbitrary IP protocol number or using predefined string for user readability (such as TCP 6 or UDP 17). I wonder if this is by design or there is a bug in the pyangbind plugin?

Regards,
freeze

**Comment by robshakir** [comment]
Hi!

Thanks for reporting this -- yes, this was a bug whereby the handling of an `identityref` inside a `union` in a `typedef` statement was not correctly resolved.

I'm just about to commit a fix to `master` for this. Please can you pull the repo and re-test? I've added a test-case that covers this functionality too.

Kind regards,
r.

**Comment by freeze91** [comment]
Hi,

Awesome, the last commit works perfectly in my case. Thank's for the fast response.

Regards,
freeze

**Comment by robshakir** [comment]
Great, thanks. I have a few pending changes but this will be within the next PyPI release.

Cheers,
r.

**Comment by kvikas** [comment]
Hi @robshakir did this change make it to latest PyPI release? The PyPI version I'm using (0.5.8) seems to have the same issue.

**Comment by robshakir** [comment]
@kvikas - it didn't just yet, I'm just batching up a set of updates to submit. I'll aim to push this at the latest tomorrow.

r.

**Comment by kvikas** [comment]
Thanks @robshakir . Would you be able to merge and include [this PR](https://github.com/robshakir/pyangbind/pull/92) when you push? Since `requirements.txt` is not included in dist tarball, `pip install` from source tarball fails.
