### ISSUE TITLE
pybind deserialize failing

### ISSUE THREAD

**Issue by jbrentfoster** [robshakir/pyangbind#86]
Hi, my script is failing and hoping you can help out.  The script, yang file and binding files are attached.

The error is shown below.  Any suggestions?
[testpyangbind_epnm.zip](https://github.com/robshakir/pyangbind/files/411599/testpyangbind_epnm.zip)

[gibson@rickenbacker yangtesting]$ python2.7 testpyangbind_epnm.py
hello from Python 2.7.12 (default, Jun 29 2016, 15:48:48)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
The REST URI is https://10.135.7.222/restconf/data/v1/cisco-customer:customer
{
  "header": {
    "firstIndex": 0,
    "lastIndex": 0
  },
  "data": {
    "customer": {
      "description": "default customer",
      "name": "Infrastructure",
      "fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
    }
  }
}
Traceback (most recent call last):
  File "testpyangbind_epnm.py", line 42, in <module>
    cust = pbj.loads(jsonreply, cisco_customer, "customer")
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/pybindJSON.py", line 53, in loads
    path_helper=path_helper, extmethods=extmethods, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/serialise.py", line 207, in load_json
    tmp = base_mod_cls(path_helper=False)
TypeError: 'property' object is not callable

**Comment by robshakir** [comment]
The bindings file that you have in the archive does not have the the "/data/customer" list that you are trying to deserialise to defined within it. 

```
[~/Downloads/testpyangbind_epnm]
(11:27 - s008) piccolo> grep "data" cisco_customer.py
```

There are also missing dependencies to be able to regenerate the bindings (imported YANG modules) so I can't validate the loads call for you. However, it looks like you have the name of the class that you want to deserialise to defined incorrectly. If you are not using `--split-class-dir` then the name of the container is re-mapped so that it is unique, so for example if I were to want to deserialise just the `customer` JSON that you supplied then this would be done via:

```
import pyangbind.lib.pybindJSON as pbj
import cisco_customer

obj = """{
"description": "default customer",
"name": "Infrastructure",
"fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
}"""

x = pbj.loads(obj, cisco_customer, "yc_customer_cisco_customer__customer")

print x.get(filter=True)
```

`yc_customer_cisco_customer__customer` is the mapped name of object which is included in the `/data/customer` list. If `--split-class-dir` is used, then equally you can import to the customer class from the `bindings.data.customer` module.

HTH,
r.

**Comment by jbrentfoster** [comment]
Ok, I fixed the binding with updated YANG file.  I added the whole archive so you can see the other dependencies.  I processed all the files with the process_yang.sh shell script (also included).  Snip from that...
pyang -p $YANGPATH --plugindir $PYBINDPLUGIN -f pybind -o epnm_yang_bindings/$FILENAME.py $f

Now the cisco_customer.py file does have the reference to the "data" list.  Would you mind having another look now and see where I'm going wrong?  If you can help be get the sample JSON loaded with the correct syntax I think I can take it from there (or at least I'll be headed in the right direction!)

Thanks,

Brent
[testpyangbind_epnm.tar.gz](https://github.com/robshakir/pyangbind/files/411916/testpyangbind_epnm.tar.gz)

**Comment by robshakir** [comment]
What format is the JSON that you have supplied? It does not seem to be compliant either with the PyangBind internal JSON or the IETF JSON encoding. 

That is to say, in PyangBind, this list would be serialised thus:

```json
{
    "response-message": {
        "data": {
            "customer": {
                "test": {
                    "fdn": "test"
                }
            }
        }
    }
}
```

A formal compliant with the IETF JSON encoding would look like this (note that this uses a JSON array to represent a list, rather than a keyed JSON object like the PyangBind representation).

```json
{
    "cisco-customer:response-message": {
        "data": {
            "customer": [
                {
                    "fdn": "test"
                }
            ]
        }
    }
}
```

If it is generated by confd, then you can get the latter output type by using "Accept: application/vnd.yang.data+json".

r.

**Comment by jbrentfoster** [comment]
Rob,
Many thanks for trying to help me here.  I realized that the YANG schema file I'm getting from the developer still didn't match the JSON.  So, I manually fixed it myself (see "cisco-customer.yang" in the attached repository).  I believe it matches now.  Here is the pyang tree output...

module: cisco-customer
   +--rw customer-list
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   |  +--rw data
   +--rw header
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   +--rw data
      +--rw customer* [fdn]
         +--rw fdn            com:fdn
         +--rw name?          string
         +--rw description?   string
         +--rw status?        string

I also rebuilt the bindings based on that updated file.  Finally, I cleaned up the JSON and put it in a file (see "testjson.txt").  I modified the script to just read from the file (ignoring the JSON direct from the server).  So, this should eliminate that as an issue.  

The primary changes to the script are...

jsonreply = open('testjson.txt','r').read()
print jsonreply
jsonreply = jsonreply.replace('\n', '')
cust = pbj.loads(jsonreply, cisco_customer, "data")

[testpyangbind_epnm_2.tar.gz](https://github.com/robshakir/pyangbind/files/412126/testpyangbind_epnm_2.tar.gz)

Now, I'm still seeing an error (output below).  I think I'm very close, I really appreciate your patience!

{
    "header": {
        "firstIndex": 0,
        "lastIndex": 0
        },
    "data": {
        "customer": {
        "description": "default customer",
        "name": "Infrastructure",
        "fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
        }
    }
}

Traceback (most recent call last):
  File "testpyangbind_epnm.py", line 45, in <module>
    cust = pbj.loads(jsonreply, cisco_customer, "data")
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/pybindJSON.py", line 53, in loads
    path_helper=path_helper, extmethods=extmethods, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/serialise.py", line 207, in load_json
    tmp = base_mod_cls(path_helper=False)
TypeError: 'property' object is not callable

**Comment by robshakir** [comment]
The file in the zip provided does not match the schema that you're trying to deserialise for. `customer` is defined to be a list in this YANG module, whereas (as per my comment above) your output indicates that it should be a container.

If you edit the `cisco-customer.yang` file as per the following diff:

```
--- epnm-restconf-data-schema/yang/cisco-customer.yang	2016-08-10 14:30:35.000000000 -0600
+++ cisco-customer.yang	2016-08-10 16:00:07.000000000 -0600
@@ -33,8 +33,7 @@ module cisco-customer {
     }
     container data {
         description "holder for list of any objects";
-        list customer {
-            key "fdn";
+        container customer {
             description "customer details";
             uses customer-grouping;
         }   
```

Then you can load the `testjson.txt` file using the first two examples in the below. If you rather use a JSON output that matches the fact that this is a list in the original module - then one can successfully deserialise JSON (see the bottom two examples).

```python

# tbind is generated by: pyang --plugindir $PYBINDPLUGIN -f pybind -o tbind.py -p epnm-restconf-data-schema cisco-customer.yang
# changed customer to a container
import tbind
import pyangbind.lib.pybindJSON as pbj
import json

y = pbj.load('testjson.txt', tbind, "cisco_customer")
print pbj.dumps(y)

# tbinddir generated by pyang --plugindir $PYBINDPLUGIN -f pybind --split-class-dir tbinddir -p epnm-restconf-data-schema cisco-customer.yang
import tbinddir
z = pbj.load('testjson.txt', tbinddir, "cisco_customer")
print pbj.dumps(z)

# using the module with a list in it and IETF JSON format
testjson = """
{
    "header": {
        "firstIndex": 0,
        "lastIndex": 0
        },
    "data": {
        "customer": [
        	{
	        	"description": "default customer",
	        	"name": "Infrastructure",
	        	"fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
	        }
        ]

    }
}"""
from epnm_yang_bindings import cisco_customer as origcisco_customer
q = pbj.loads_ietf(testjson, origcisco_customer, "cisco_customer")
print pbj.dumps(q, mode="ietf")

# using pyangbind internal JSON format
testjson = """
{
    "header": {
        "firstIndex": 0,
        "lastIndex": 0
        },
    "data": {
        "customer": {
        	"MD=CISCO_EPNM!CUSTOMER=Infrastructure": {
	        	"description": "default customer",
	        	"name": "Infrastructure",
	        	"fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
	        }
        }
    }
}"""
r = pbj.loads(testjson, origcisco_customer, "cisco_customer")
print pbj.dumps(r)
```

The only issue I see with pyangbind here is that we should probably be more explicit when a list is supplied and we don't find a way to properly deserialise it.

r.

**Comment by jbrentfoster** [comment]
Rob,

I have it working now!  Granted you had to spoon feed me, but I really appreciate it.  I'm understanding much better now how all this works.  As you probably guessed I'm a novice with both YANG and Python.  Thanks for your patience!

In case others hit my same issues, I'll try to summarize what I had wrong:

1) My YANG schema file did not match the JSON I was trying to deserialize.  I had to modify this file (with your guidance) to properly match the JSON.

2) I was trying to create a module with all the bindings in one flat directory.  However, this was the wrong way to do it.  I needed to use the `--split-class-dir` option to create this structure.

Once I fixed these issues, here is the outcome...
Input YANG schema...
```
module: cisco-customer
   +--rw customer-list
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   |  +--rw data
   +--rw header
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   +--rw data
      +--rw customer
         +--rw fdn?           com:fdn
         +--rw name?          string
         +--rw description?   string
         +--rw status?        string
```


Input JSON
```
{
    "header": {
        "firstIndex": 0,
        "lastIndex": 0
        },
    "data": {
        "customer": {
            "description": "default customer",
            "name": "Infrastructure",
            "fdn": "MD=CISCO_EPNM!CUSTOMER=Infrastructure"
        }
    }
}
```

Relevant Python code...
```
import tbinddir
import pyangbind.lib.pybindJSON as pbj
cust = pbj.loads(jsonreply, tbinddir, "cisco_customer")
print "The customer name is: " + cust.data.customer.name
print "The customer description is: " + cust.data.customer.description
print "The customer fdn is: " + cust.data.customer.fdn
```

After running the script...
```
The customer name is: Infrastructure
The customer description is: default customer
The customer fdn is: MD=CISCO_EPNM!CUSTOMER=Infrastructure
```

**Comment by robshakir** [comment]
Hi,

No problems. Please open a new issue if you have further problems.

Cheers,
r.
