### ISSUE TITLE
Deserializing a List is Failing

### ISSUE THREAD

**Issue by jbrentfoster** [robshakir/pyangbind#87]
I'm trying to tackle a more complex response and I'm seeing issues.  I suspect my YANG module is again not matching the JSON, but I'm not entirely sure.  I want to rule out any bug with pyangbind, as well.  Attached all the project files.  The sample JSON is in the `testjson_vc.txt` file.

A snip of the YANG tree is shown below where the `data` container has a `virtual-connection` list...

```
module: cisco-virtualconnection
   +--rw virtual-connection-list
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   |  +--rw data
   +--rw header
   |  +--rw firstIndex?   int32
   |  +--rw lastIndex?    int32
   +--rw data
      +--rw virtual-connection* [fdn]
         +--rw fdn                       com:fdn
         +--rw discovered-name?          string
         +--rw description?              string
         +--rw admin-state?              identityref
         +--rw oper-state?               identityref
```
I'm calling pyang with this code...

`cust = pbj.loads(jsonreply, tbinddir, "cisco_virtualconnection")`

The error I'm seeing is...
```
Traceback (most recent call last):
  File "testpyangbind_epnm_vc_json.py", line 17, in <module>
    cust = pbj.loads(jsonreply, tbinddir, "cisco_virtualconnection")
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/pybindJSON.py", line 53, in loads
    path_helper=path_helper, extmethods=extmethods, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/serialise.py", line 248, in load_json
    path_helper=path_helper, skip_unknown=skip_unknown)
  File "/usr/lib/python2.7/site-packages/pyangbind/lib/serialise.py", line 280, in load_json
    key_order = d[key].keys()
AttributeError: 'list' object has no attribute 'keys'
```

Any pointers on debugging these in the future would be appreciated.  I tried to go to the referenced lines in the traceback, but couldn't sort out the issue.

[testpyangbind_epnm_vc.tar.gz](https://github.com/robshakir/pyangbind/files/414185/testpyangbind_epnm_vc.tar.gz)

**Comment by robshakir** [comment]
Please read the comments that I added to the other issue relating to the type of JSON that you are trying to deserialise.

1. You will probably want to look at `loads_ietf` rather than `loads`.
2. You will need to discuss with the implementation that is producing the JSON output what standard they are aiming to comply to - particularly how they represent the source module in an `identityref` value when serialising it (hint: `ns2:bi-direction` is probably not a valid value).

HTH, 
r.

**Comment by jbrentfoster** [comment]
Thanks I will discuss this with the developers of the server. There are apparently issues with their YANG modules and JSON responses. I don't think I can make much progress until we get that fixed.

**Comment by robshakir** [comment]
If this is confd then I believe that older releases did not return IETF-encoded JSON (like PyangBind they had a format before this was ratified) - no inter-op testing has been done between PyangBind and that format.

r.

**Comment by jbrentfoster** [comment]
Actually once I fixed all the problems with the identityref names and the YANG module that did not match the JSON model this deserialized perfectly. So, I don't think there is an interop issue with the JSON format.
