### ISSUE TITLE
Error while running pyangbind 0.5.6

### ISSUE THREAD

**Issue by ashishk1994** [robshakir/pyangbind#91]
I am doing the following steps:

1. Current directory
Command: ls -la 
Output: 

total 96
drwxrwxr-x. 2 jenkins jenkins  4096 Sep 21 11:28 .
drwxrwxr-x. 4 jenkins jenkins  4096 Sep 21 11:28 ..
-rw-rw-r--. 1 jenkins jenkins  2740 Sep 21 11:28 bits.patch
-rw-rw-r--. 1 jenkins jenkins  6258 Sep 21 11:28 config.yang
-rw-rw-r--. 1 jenkins jenkins 16294 Sep 21 11:28 **ietf-inet-types.yang**
-rw-rw-r--. 1 jenkins jenkins 17389 Sep 21 11:28 ietf-lisp-address-types.yang
-rw-rw-r--. 1 jenkins jenkins 15896 Sep 21 11:28 ietf-yang-types.yang
-rw-rw-r--. 1 jenkins jenkins 10749 Sep 21 11:28 odl-lisp-proto.yang
-rw-rw-r--. 1 jenkins jenkins  7077 Sep 21 11:28 odl-mappingservice.yang
-rw-rw-r--. 1 jenkins jenkins  2373 Sep 21 11:28 yang-ext.yang

2. 
Command: pyang ./ietf-inet-types.yang
Output: Successful run

3. 
Command : /usr/bin/env python -c 'import pyangbind; import os; print "%s/plugin" % os.path.dirname(pyangbind.__file__)'
Output: Successful run

4. 
Command: echo $PYBINDPLUGIN
Output: /tmp/tmp.OWrypOnBUSrobot_venv/lib/python2.7/site-packages/pyangbind/plugin

5. 
Command: pyang --plugindir $PYBINDPLUGIN -f pybind --build-rpcs --split-class-dir ./LISPFlowMappingYANGBindings    ./ietf-inet-types.yang

Output: Error

Traceback: 
Traceback (most recent call last):
```
  File "/tmp/tmp.OWrypOnBUSrobot_venv/bin/pyang", line 434, in <module>
    run()
  File "/tmp/tmp.OWrypOnBUSrobot_venv/bin/pyang", line 408, in run
    emit_obj.emit(ctx, modules, fd)
  File "/tmp/tmp.OWrypOnBUSrobot_venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 211, in emit
    build_pybind(ctx, modules, fd)
  File "/tmp/tmp.OWrypOnBUSrobot_venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 372, in build_pybind
    t = find_definitions(defnt, ctx, m[1], m[0])
  File "/tmp/tmp.OWrypOnBUSrobot_venv/lib/python2.7/site-packages/pyangbind/plugin/pybind.py", line 683, in find_definitions
    (module.arg) + "but could not")
AttributeError: expected to be able to find module ietf-inet-types, but could not

```

Can someone please tell me why this is happening, It should run successfully as I am runnning the pyang using correct parameters and from same directory.

**Comment by ashishk1994** [comment]
This is ietf-inet-types.yang model that I am using. 

https://git.opendaylight.org/gerrit/gitweb?p=mdsal.git;a=blob_plain;hb=refs/heads/stable/beryllium;f=model/ietf/ietf-inet-types/src/main/yang/ietf-inet-types.yang

**Comment by ashishk1994** [comment]
@robshakir Any help!

**Comment by robshakir** [comment]
Hi @ashishk1994 - I'll check this out when I get a moment. Hopefully by the end of the week.

**Comment by robshakir** [comment]
Hi @ashishk1994,

Please try the current commit - this issue should be resolved. Apologies for the delay.

Cheers,
r.

**Comment by robshakir** [comment]
Closing as this appears to be resolved and a fixed version was rolled out to PyPI.
