### ISSUE TITLE
Help wanted -  Can i use it as a YANG Parser Library?

### ISSUE THREAD

**Issue by sureshkvl** [robshakir/pyangbind#96]
Does it exposes API? Can i use it inside the code.
The scenario is like this,

I have a YANG file,  
In my program, i need to parse the yang file and convert in to JSON or local objects (some models which already supported by the library). These converted data  will be consumed by my program.

Is it possible to do with this pyangbind?

Thanks
suresh

**Comment by robshakir** [comment]
Hi Suresh,

I'm not entirely clear what the question is here. YANG is a schema description language, JSON is a data serialisation format. So when you say "convert YANG to JSON" - what are you expecting to need to ingest? A JSON document whose schema is described in YANG?

If that is the case, then yes, you can use PyangBind to load that JSON document into bindings that are generated by PyangBind, and then you are free to access the structures that it stores. You'll probably find the `xpathhelper` classes useful for navigating that data.

If you need to read an arbitrary YANG file at run-time, then PyangBind isn't designed to do that - you'll probably need [pyang](https://github.com/mbj4668/pyang) if you want Python, or [goyang](https://github.com/openconfig/goyang) if you are OK with Go.

r.

**Comment by sureshkvl** [comment]
Hi Rob,

I mentioned JSON as sample format . It can be any.

>If you need to read an arbitrary YANG file at run-time, then PyangBind isn't designed to do that - >you'll probably need pyang if you want Python, or goyang if you are OK with Go.
Yes. YANG file will be arbitrary file in run time.  My program need to read that file and retrieve the config and rpc details from the YANG file, and use it for my needs. For that i am looking the YANG parser. (something similar to https://github.com/corenova/yang-js)

As you pointed, let me check the pyang.  

Thanks
suresh

**Comment by robshakir** [comment]
Sure, no worries - PyangBind isn't designed for this

Cheers,
r.

**Comment by lhchang** [comment]
Hi Rob, 
I would like to actually use Pyangbind in the case you have mentioned - loading JSON data (received from outside) and load it into the bindings so I can easily pick out values for further processing. I am rather new to YANG and still trying to figure out details, but essentially I am loading what is supposedly a JSON that conforms to the YANG models of interest (ietf-acldns, ietf-access-control-list, ietf-mud). I am trying to follow the `test_006_ietf_deserialise` example in /tests/xpath/04-root/run.py but I am encountering the following error when I try to use the load_ietf_json method: 

`KeyError: u'key value must be valid, {\'error-string\': \'name must be of a type compatible with leafref\', \'generated-type\': \'YANGDynClass(base=ReferenceType(referenced_path=\\\'/acl:access-lists/acl:acl/acl:name\\\', caller=self._path() + [\\\'name\\\'], path_helper=self._path_helper, require_instance=True), is_leaf=True, yang_name="name", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace=\\\'urn:ietf:params:xml:ns:yang:ietf-mud\\\', defining_module=\\\'ietf-mud\\\', yang_type=\\\'leafref\\\', is_config=True)\', \'defined-type\': \'leafref\'}'`

Looking back at the ietf-mud.yang module, it looks like that leaf 'name' is of type leafref so I am not sure what the error means when it says that `name must be of type compatible with leafref`. For reference, I've attached the JSON that I am using.

[mudfile.txt](https://github.com/robshakir/pyangbind/files/1809053/mudfile.txt)

I'd appreciate any help in helping me better understand why the error occurs. Sorry if I've misused any terminology, and thank you!
