### ISSUE TITLE
Nested typedef not supported

### ISSUE THREAD

**Issue by ddr31** [robshakir/pyangbind#98]
The following YANG module "short.yang" shows a typedef for "sname" at outer scope:

```
module short {
  namespace "http://anywhere.com";
  prefix p;

  typedef sname {
    type string {
      length "1..60";
    }
  }

  container a {
    leaf b {
      type sname;
    }
  }
}
```
The code above builds fine:
$ pyang --plugindir $PYBINDPLUGIN -f pybind -o ~/out.py short.yang
$

But if you move the typedef inside the container, the build fails:

```
module short {
  namespace "http://anywhere.com";
  prefix p;

  container a {
    typedef sname {
      type string {
      length "1..60";
      }
    }

    leaf b {
      type sname;
    }
  }
}
```

$ pyang --plugindir $PYBINDPLUGIN -f pybind -o ~/out.py short.yang
FATAL: unmapped type (sname)
[ 'int32',
  'int16',
  'string',
  'uint8',
  'boolean',
  'int8',
  'uint64',
  'binary',
  'decimal64',
  'uint16',
  'int64',
  'uint32',
  'empty']
u'sname'
False
$

**Comment by robshakir** [comment]
Please see the fix that is in #102 - this was due to `container` not being checked for `typedef` statements.

**Comment by ddr31** [comment]
Thanks Rob! I verified the changes and they work like a champ ;).

**Comment by robshakir** [comment]
No problems, I just pushed an updated version of pyangbind to PyPI with this fix in it.
