### ISSUE TITLE
Unit tests using unittest module fail when DEL=true set in yang_tests.sh

### ISSUE THREAD

**Issue by timmartin** [robshakir/pyangbind#99]
If you set `DEL=true` in `yang_tests.sh`, then the following tests are reported as failing:

- tests/misc
- tests/presence
- submodules

This is because these tests use `unittest.main`, which rejects the `-k` argument used to indicate that the output should not be deleted.

**Comment by robshakir** [comment]
Thanks - per comments in #100, this will be resolved as I merge #101.
